### ISSUE TITLE
Distorted decoding of H.264 progressive stream

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#103]
_From [4Selur](https://code.google.com/u/117995077701246787916/) on November 19, 2012 07:26:30_

> What steps will reproduce the problem?
Create an avisynth script and load source through FFVideoSource
e.g.
FFVideoSource("H:\test\t1ex.mkv",cachefile="H:\Temp\t1ex.ffindex",threads=1)

> What is the expected output? What do you see instead?
I expected a proper picture, I saw a distorted picture

> What version of the product are you using? On what operating system?
tried: ffms2- r725 -icl-4, and ffms-2.17
Windows 7 64bit and Windows 7 32bit
using Avisynth 2.6

---
Attached a sample file which causes the problem. (encoded with x264, plays fine in mplayer, mpc-hc, ffplay)
Remuxing to mp4 and m2ts doesn't help either. (tried to make sure it's not somehow related to mkv container)

**Attachment:** [t1ex.mkv](http://code.google.com/p/ffmpegsource/issues/detail?id=103)

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=103_

**Comment by myrsloik** [comment]
Reproduced. When playing it straight the last frames are green/grey/corrupted. Seeking to beyond the first 1/3 of the file also seems to give corrupted output.

File is corrupt?

**Comment by dwbuiten** [comment]
You may have better luck pinging @selur by his github name.

**Comment by Selur** [comment]
Sorry, but I don't even recall the issue (posted it November 2012 ;))

I doubt that the file was corrupt since:
> encoded with x264, plays fine in mplayer, mpc-hc, ffplay
