### ISSUE TITLE
Seeking audio throws exception in 64bit build

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#112]
_From [praks411](https://code.google.com/u/108805631768981425196/) on March 27, 2013 04:36:22_

What steps will reproduce the problem?
1. Open any video file with audio. 
2. While try to seek audio exception in generated FFMS_GetAudioSource
3. Name of exception "FFMS_ERROR_SEEKING". Only happens with 64bits build.
What is the expected output? What do you see instead? 
 was expecting seek audio frame but it throws exception.

What version of the product are you using? On what operating system? ffm2_2_17 on Windows 7 64bits Please provide any additional information below. However everything work fine for 32bits.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=112_

**Comment by myrsloik** [comment]
Probably not still broken or more people would've complained.
