### ISSUE TITLE
newer versions clamp fullrange h264 to 16-235 (since r16 onwards)

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#113]
_From [hiddevdl](https://code.google.com/u/100632219396377452343/) on May 30, 2013 11:44:26_

What steps will reproduce the problem? 1. download fullrange.mp4 and fullrange.avs
2. open avs file in viewer What is the expected output? What do you see instead? Expecting to see a fullrange frame. Like in the older ffms2 version r15 . Instead I see a clamped version (the highlights in the button and the shirt just below are clipped. when using ffms2, only the button shows clipping) What version of the product are you using? On what operating system? on avisynth 2.60, window 7 ultimate Please provide any additional information below.

**Attachment:** [fullrange.mp4 fullrange.avs](http://code.google.com/p/ffmpegsource/issues/detail?id=113)

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=113_

**Comment by myrsloik** [comment]
The output yv12 has 0-255 value so it appears to work. Possible clipping in the vdub conversion when looking at it.
