### ISSUE TITLE
[AVC] GREY FRAMES AFTER SEEKING

### ISSUE THREAD

**Issue by AtakSnajpera** [FFMS/ffms2#137]
ffms2.19

MY SCRIPT
LoadPlugin("ffms2.dll")
FFVideoSource("video.mkv",threads=1)
Trim(1457,2877)

RESULT 
FEW GREY CORRUPTED FRAMES 
Screenshot -> http://s24.postimg.org/62422rcv9/2_avs_snapshot_00_00_2013_11_10_18_28_09.png

SAMPLE -> http://speedy.sh/kSjg3/video-chunk.mkv

BTW. frame 1457 is an I-Frame

**Comment by myrsloik** [comment]
Sample is gone, can't test.
