### ISSUE TITLE
Possible to index just video?

### ISSUE THREAD

**Issue by timredfern** [FFMS/ffms2#142]
Hi, apologies if this isn't a bug and I just don't understand FFMS2. FFMS2 is an invaluable part of a project I'm building.

However-

I'm building a video editing system and I'm not using the audio embedded in video files at all. I want to just ignore it.

If I present FFMS2 with a video file for which it doesn't understand the audio, it fails to index and won't retrieve the video frames. If I manually remove the audio track from the file, it works..

I'm using this line to load the video files:

<code>
index = FFMS_MakeIndex(filename.c_str(), 0, 0, NULL, NULL, FFMS_IEH_IGNORE, NULL, NULL, &err);
</code>

My understanding from the documentation at http://ffmpegsource.googlecode.com/svn/trunk/doc/ffms2-api.html

If I use

<code>
FFMS_Index *FFMS_MakeIndex(const char *SourceFile, int IndexMask, int DumpMask,
	TAudioNameCallback ANC, void *ANCPrivate, int ErrorHandling,
	TIndexCallback IC, void *ICPrivate, FFMS_ErrorInfo *ErrorInfo);
</code>

and pass 0 to IndexMask, I believe it should ignore all audio tracks. It doesn't seem to be the case. I've also tried all options for ErrorHandling which are:

<code>
typedef enum FFMS_IndexErrorHandling {
	FFMS_IEH_ABORT = 0,
	FFMS_IEH_CLEAR_TRACK = 1,
	FFMS_IEH_STOP_TRACK = 2,
	FFMS_IEH_IGNORE = 3
} FFMS_IndexErrorHandling;
</code>

however no matter what I do, these video files with unreadable audio always return a nullptr from FFMS_MakeIndex

Is this a bug?

Regards

Tim Redfern

**Comment by myrsloik** [comment]
Appears to work now.
