### ISSUE TITLE
Indexing small video files < 1MB

### ISSUE THREAD

**Issue by timredfern** [FFMS/ffms2#144]
I've been wracking my brains as to why FFMS2 is failing to index some of my files

I've realised that its caused by the hashing mechanism failing at line 450 of FFMS_Index::CalculateFileSignature where the source file is <1MB.

I really need to deal with small video files, so I'm looking at changing the hash size or creating the option to disable the check. Would welcome any opinions on the best way to go about it?

Tim Redfern

**Comment by myrsloik** [comment]
Worked for me on a 44kb file recently.
