### ISSUE TITLE
Black image when reading raw/pal8 AVI file

### ISSUE THREAD

**Issue by myier** [FFMS/ffms2#148]
Hi, I am finally able to share an AVI file for which frames extracted by FFMS2 are filled with zeros (= black). The codec is raw video, pixel format pal8. Here is the link to the compressed video: http://free-astro.vinvin.tf/videos/videos-tests/0-11-51-265.avi.xz . That seems to be a common format for the previous generation of astronomy capture sequences.
FFMPEG is able to decode these films.
That'd be great if you could fix this! Thanks!

**Comment by myrsloik** [comment]
Confirmed to still be broken. No idea what to do about it.

**Comment by myrsloik** [comment]
Fixed
