### ISSUE TITLE
FFInfo() Data Stuck for several frames

### ISSUE THREAD

**Issue by ndjamena** [FFMS/ffms2#164]
I've been trying to use FFVideoSource to find chapter positions in my MakeMKV Blu Ray rips.  Since my WDTV live will only start play from I-Frames I need to know the frame type and Time code for each frame, however the numbers are making a habit of freezing at a certain position and not updating for quite a few frames afterwards.  To make it even more annoying AVISynth caches these frames with the bad info so I have to go back and play another part of the video before trying again.  seekmode=0 doesn't seem to do anything at all that I can see.

Also, after I've written in the new chapters the old index immediately becomes invalid so I need to reindex the files in order to look at them again.  Is this entirely necessary?

**Comment by myrsloik** [comment]
Test file is gone, issue is old so can't retest. Reopen with new sample if still a problem.

**Comment by ndjamena** [comment]
It works on pretty much any h.264 MKV file I care to throw at it, I'm looking at the Blu Ray rip of The Husbands of River Song at the moment and I've got the frame 7867 info repeating 4 times.  7863, 7867, 7867, 7867, 7867, 7868.

I just need to open the file in VirtualDub, jump to any time in a video, press forward six or seven times, then start pressing backwards repeatedly and chances are 4 times out of 5 the numbers will start getting screwed up.

I don't know what's causing it, if it's VirtualDub somehow...  I've been switching between AVISynth versions and they all do it, I don't know if there's something on my PC the filter is using (intel decoder?).

I've given up on chapters and don't really care anymore but on my computer at least the problem still exists.

**Comment by myrsloik** [comment]
Can you verify that it's fixed with this build?
https://www.dropbox.com/s/snepd7t006fpg8o/ffms2000-test8.7z?dl=1

**Comment by myrsloik** [comment]
Probably fixed
