### ISSUE TITLE
ffinfo() error when using ffvideosource()'s vfr->cfr conversion

### ISSUE THREAD

**Issue by sneaker2** [FFMS/ffms2#172]
When using ffvideosource()'s vfr->cfr conversion by setting the fpsnum and fpsden parameters ffinfo() generates an error message: "I don't know what "FFVFR_TIME" means ([ScriptClip], line X)"

This also has the side effect of slowing down the script considerably.

**Comment by myrsloik** [comment]
Now all per frame variables are always set and ffinfo will simply show <unknown> as the vfr time value and 'U' for the frame type when rff mode is active.
