### ISSUE TITLE
ffaudiosource()'s adjustdelay ignores positive video delays

### ISSUE THREAD

**Issue by sneaker2** [FFMS/ffms2#174]
ffaudiosource()'s adjustdelay ignores positive video delays instead of deleting samples like it would be supposed to do.

Sample:
https://mega.co.nz/#!w412mAzJ!sV2LwE_XDtRyoawRJgS-3OAiBx2qws7y-0pinrSqhfg

**Comment by tophf** [comment]
I think last time it worked was three years ago with v2.17.

**Comment by myrsloik** [comment]
Is this still broken?

**Comment by sneaker2** [comment]
No.
(Tested with your test build from here: http://forum.doom9.org/showpost.php?p=1719379&postcount=2013)
