### ISSUE TITLE
FMSindex.exe crashes with MKV (UT VIDEO)

### ISSUE THREAD

**Issue by AtakSnajpera** [FFMS/ffms2#180]
Screenshot -> http://i.cubeupload.com/vFgSYI.png

Sample -> https://mega.co.nz/#!9E1QGCDI!9tgqRa59p1OIejmRvIBB5angl-0oHd6FYc-6JXRBCJo

General
Unique ID                                : 251663673212891099823893280277094579207 (0xBD54A910FDD03E069989C2A9D671BC07)
Complete name                            : C:\temp\RipBot264temp\job1\video-UTVideo-problem.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 200 MiB
Duration                                 : 24s 600ms
Overall bit rate                         : 68.3 Mbps
Encoded date                             : UTC 2014-10-24 13:58:11
Writing application                      : mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
Writing library                          : libebml v1.3.0 + libmatroska v1.4.1
DURATION                                 : 00:00:24.600000000
NUMBER_OF_FRAMES                         : 255
NUMBER_OF_BYTES                          : 209977816
_STATISTICS_WRITING_APP                  : mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
_STATISTICS_WRITING_DATE_UTC             : 2014-10-24 13:58:11
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : YUV
Codec ID                                 : V_MS/VFW/FOURCC / ULH2
Codec ID/Info                            : Ut Video Lossless Codec
Codec ID/Hint                            : Ut Video
Bit rate                                 : 66.9 Mbps
Width                                    : 2 048 pixels
Height                                   : 1 152 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Compression mode                         : Lossless
Default                                  : Yes
Forced                                   : No

**Comment by myrsloik** [comment]
lavf is the default and only demuxer now
