### ISSUE TITLE
Flicks between interleave audio

### ISSUE THREAD

**Issue by Paul-Zi** [FFMS/ffms2#181]
Formed flicks in the audio when "interleave, duration" equal "interleave, preload duration".
On version ffms2-r683 (2.18) there is no problem.

Video: https://drive.google.com/file/d/0B0_wUK5H5ZI4c0hqblRyaEdiVzg/view?usp=sharing

**Comment by myrsloik** [comment]
Seems to work now in my own build.

**Comment by Paul-Zi** [comment]
Thank you very much!
2 мая 2015 г. 21:49 пользователь "Fredrik Mellbin" <notifications@github.com>
написал:

**Comment by Paul-Zi** [comment]
I tested the version 2.21 - clicks still present.

**Comment by myrsloik** [comment]
Doh

**Comment by myrsloik** [comment]
This really sounds the same no how I try to play it back. I'm not sure what the problem you're referring to is.

**Comment by Paul-Zi** [comment]
Flicks have when playing in MPC HC new versions, although in VLC Player and old version of the MPC HC no flicks. Strangely it all. Probably malformed format record. I'll be using an older version of ffms (2.18) for this video format.
Thanks you!
