### ISSUE TITLE
Color levels are messed up in yuvj420p FRAPS videos

### ISSUE THREAD

**Issue by nixxquality** [FFMS/ffms2#182]
Here is an example video that displays this behavior: http://www.mediafire.com/download/zkui7hkk2lc8iyx/XR_3DA+2014-05-02+23-02-41-33.avi

Color levels are messed up until you add a line calling ```ColorYUV(levels="PC->TV")```

I'm not sure if this is fixed in HEAD, as I can not compile FFMS2 myself.

**Comment by myrsloik** [comment]
You have fullrange yuv and you get fullrange yuv. Not a bug.
You can automate the PC->TV levels selection by checking the global FFCOLOR_RANGE in avisynth.
