### ISSUE TITLE
FFMS_CreateVideoSource fails in files with many tracks

### ISSUE THREAD

**Issue by nixxquality** [FFMS/ffms2#185]
When using the FFMS2 API and making a VideoSource in a file with >32 tracks, the operation fails even if the video track is among the first 32.

The error thrown is a ```(ErrorType = FFMS_ERROR_INDEX, SubType = FFMS_ERROR_INVALID_ARGUMENT)```

Example file: http://www.nyaa.se/?page=view&tid=615715

**Comment by dwbuiten** [comment]
Does this still happen after 29e071c5c9f41820918487a975626f0427d2888b?

**Comment by nixxquality** [comment]
Can you give me a dll to test with? I'm unable to compile myself.

**Comment by dwbuiten** [comment]
Here's a barebones 64-bit MSVC build:

https://www.dropbox.com/s/ogw6z29s4qgteti/ffms-git-HEAD.7z?dl=0

**Comment by nixxquality** [comment]
Sorry, could you give me a 32-bit build instead?

**Comment by dwbuiten** [comment]
https://www.dropbox.com/s/609th14rgfq2eo6/FFMS-git-HEAD-32.7z?dl=0

**Comment by nixxquality** [comment]
No, it is not fixed, as far as I can tell.

**Comment by dwbuiten** [comment]
Have you tried forcing the lavf demuxer btw?

**Comment by nixxquality** [comment]
Yes, I am already forcing the lavf demuxer.

**Comment by dwbuiten** [comment]
Actually, it's likely due to:

```C
int IndexMask;
```

**Comment by myrsloik** [comment]
Try this compile from my possibly fixed branch:
https://www.dropbox.com/s/6vxgt5npuyifjjw/ffms2-test1.7z?dl=1

**Comment by nixxquality** [comment]
Yup, that works.

**Comment by myrsloik** [comment]
Apparently fixed in my branch
