### ISSUE TITLE
Add brew formula

### ISSUE THREAD

**Issue by MartinDelille** [FFMS/ffms2#186]
A brew formula would be nice for easy macos dev env setup. I will try to make it. If someone has something to say about it let me know!

**Comment by dwbuiten** [comment]
Should this not be filed with brew itself?

**Comment by MartinDelille** [comment]
I don't think: it's not brew jobs to create all the formula for all the librairies in the world. Developers are the main interested in a brew formula because it make their project visible on a nice opensource platform :-)

**Comment by tgoyne** [comment]
Unless it's changed recently, homebrew actually discourages submitting forumulae for your own projects.

**Comment by MartinDelille** [comment]
yes but I will do it for you. Is it a problem?
