### ISSUE TITLE
m2ts wrong timecodes precision.

### ISSUE THREAD

**Issue by gdfs** [FFMS/ffms2#187]
Why am I getting rounded numbers. It's almost useless.
# timecode format v2
5.62008e+006
5.62013e+006
5.62017e+006
5.62021e+006
5.62025e+006
5.62029e+006
5.62033e+006
5.62038e+006
5.62042e+006
5.62046e+006
5.6205e+006
5.62054e+006
5.62058e+006
5.62063e+006
5.62067e+006
5.62071e+006
5.62075e+006
5.62079e+006
5.62083e+006
5.62088e+006
5.62092e+006
5.62096e+006
5.621e+006
5.62104e+006
5.62108e+006
5.62113e+006
5.62117e+006

**Comment by gdfs** [comment]
Use of haali splitter seems to solve this problem. Sorry.

**Comment by gdfs** [comment]
I was wrong, the issue is still there.
This is the end of the file with timecodes: 
1.42096e+006
1.421e+006
1.42104e+006
1.42109e+006
1.42113e+006
1.42117e+006
1.42121e+006
1.42125e+006
1.42129e+006
1.42134e+006
1.42146e+006

The start is ok:
0
41.7
83.4111
125.122
166.833
208.533
250.244
291.956
333.667
375.367
417.078
458.789
500.5
542.2
583.911

Middle of the file:
118577
118619
118660
118702
118744
118785
118827
118869
118910
118952
118994
119036
119077
119119
119161

**Comment by dwbuiten** [comment]
This is unrelaed to m2ts, but it's because of:

https://github.com/FFMS/ffms2/blob/30adccf938ab076319bbbb311daa83d98e9fda44/src/core/track.cpp#L140

It should probably be changed to use `%.02lf`.
