### ISSUE TITLE
FFAudioSource fails to load wmv; "Seeking is severely broken."

### ISSUE THREAD

**Issue by tinmanog** [FFMS/ffms2#190]
FFAudioSource fails to load wmv; "Seeking is severely broken."

General
Complete name  
Format                         : Windows Media
File size                      : 1.98 GiB
Duration                       : 52mn 33s
Overall bit rate mode          : Variable
Overall bit rate               : 5 382 Kbps
Maximum Overall bit rate       : 8 452 Kbps
Encoded date                   : UTC 2014-09-30 10:27:26.232

Video
ID                             : 2
Format                         : VC-1
Format profile                 : MP@HL
Codec ID                       : WMV3
Codec ID/Info                  : Windows Media Video 9
Codec ID/Hint                  : WMV3
Description of the codec       : Windows Media Video 9 - Professional
Duration                       : 52mn 33s
Bit rate mode                  : Variable
Bit rate                       : 5 000 Kbps
Width                          : 1 280 pixels
Height                         : 720 pixels
Display aspect ratio           : 16:9
Frame rate                     : 24.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.226
Stream size                    : 1.84 GiB (93%)
NumberOfFrames                 : 75681

Audio
ID                             : 1
Format                         : WMA
Format profile                 : Pro
Codec ID                       : 162
Codec ID/Info                  : Windows Media Audio
Description of the codec       : Windows Media Audio 10 Professional - 440 kbps, 44 kHz, 2 channel 24 bit 2-pass VBR
Duration                       : 52mn 33s
Bit rate mode                  : Variable
Bit rate                       : 362 Kbps
Channel(s)                     : 2 channels
Sampling rate                  : 44.1 KHz
Bit depth                      : 24 bits
Stream size                    : 136 MiB (7%)
NumberOfFrames                 : 6981

https://github.com/nixxquality/WebMConverter/issues/107

**Comment by qyot27** [comment]
What version/build of FFMS2 are you using?

FFMS2's handling of WMV is based on the quality of the underlying libavformat demuxer for ASF/WMV.  The "Seeking is severely broken" message occurs because it encounters one of those trip-ups with the demuxer (or the file itself, which causes the demuxer to choke on it).

It's not much consolation, but there is a patch for a rewritten ASF demuxer (based directly on the format specifications) being vetted on the Libav-devel mailing list.  The issue may evaporate if/when that gets committed upstream.

**Comment by tinmanog** [comment]
I think it's 2.20?
https://github.com/nixxquality/WebMConverter/commit/85d7a838be99ca9094ba27aca927177b587bb022

**Comment by qyot27** [comment]
http://www.mediafire.com/?hh1w66auidylj67

This is a test build of FFMS2 with the new ASF demuxer I mentioned.  Rename or move the existing ffms2.dll and copy the ffms2.dll and FFMS2.avsi from that package into whichever folder you need to have them in (as I don't know if that just uses the standard AviSynth plugins folder or not).

**Comment by nixxquality** [comment]
WebM for Retards doesn't just use FFMS2 as an AviSynth plugin, it also interfaces directly with the ffms2.dll.

I tried running it with your dll but I got the error `Additional information: Unable to find an entry point named 'FFMS_Init' in DLL 'ffms2.dll'.`

I used DLL Export Viewer to check it and it's listed there as `FFMS_Init@8`. Is this some magic calling convention?
If you could compile a dll with a calling convention Microsoft would like, that would be usable for testing.

Alternatively, @tinmanog could save your dll as Binaries/Win32/ffms2_compatible.dll, do his processing, press the Export button and save it somewhere, open it and change
```
LoadPlugin(PluginPath+"ffms2.dll")
# to
LoadPlugin(PluginPath+"ffms2_compatible.dll")
```
then load that avs file and see if it works.

**Comment by qyot27** [comment]
>I used DLL Export Viewer to check it and it's listed there as ``FFMS_Init@8``. Is this some magic calling convention?
If you could compile a dll with a calling convention Microsoft would like, that would be usable for testing.

GCC doesn't prefix underscores when using stdcall, and unfortunately there doesn't seem to be an easy way to force this when compiling for Windows (-fleading-underscore is ELF-only), so I forced it through an ifdef.  Hopefully that's all it needs.

http://www.mediafire.com/?pe3g37b73j4kjdq

**Comment by nixxquality** [comment]
Looks like you still have to do the LoadCPlugin edit, but the main program itself works now. I've implemented something to automatically load ffms2.dll as a CPlugin if it happens to be required.

If you take that mediafire dll and replace `Binaries/Win32/ffms2.dll` you should be able to test if the new asf decoder is up to scratch.

**Comment by myrsloik** [comment]
No sample file?
