### ISSUE TITLE
[AviSynth plugin] Unable to load/process 960:640 (3:2) video

### ISSUE THREAD

**Issue by Kein** [FFMS/ffms2#194]
Video in question: http://www64.zippyshare.com/v/kTIU4syL/file.html

> Format                                   : AVI
> Format/Info                              : Audio Video Interleave
> File size                                : 97.2 MiB
> Duration                                 : 12s 140ms
> Overall bit rate                         : 67.1 Mbps
> Original source form/Distributed by      : Video:YUV420|CompressV3 Audio:Speakers (VIA High Definition Audio)
> Writing application                      : DxtoryCore ver2.0.0.127
Video
> ID                                       : 0
> Format                                   : xtor
> Codec ID                                 : xtor
> Duration                                 : 11s 400ms
> Bit rate                                 : 69.8 Mbps
> Width                                    : 960 pixels
> Height                                   : 640 pixels
> Display aspect ratio                     : 3:2
> Frame rate                               : 30.000 fps
> Bits/(Pixel*Frame)                       : 3.789
> Stream size                              : 94.9 MiB (98%)

> Audio
> ID                                       : 1
> Format                                   : PCM
> Format settings, Endianness              : Little
> Format settings, Sign                    : Signed
> Codec ID                                 : 1
> Duration                                 : 12s 140ms
> Bit rate mode                            : Constant
> Bit rate                                 : 1 536 Kbps
> Channel(s)                               : 2 channels
> Sampling rate                            : 48.0 KHz
> Bit depth                                : 16 bits
> Stream size                              : 2.22 MiB (2%)
> Alignment                                : Aligned on interleaves
> Interleave, duration                     : 93 ms (2.80 video frames)

Recorded with Dxtory as YUV12 (j420p). Virtual Dub with FFMPEG plugin opens it fine. More than that, if I record it with Dxtory in 1024x768 it woks perfectly in AVS.

What gives?

**Comment by qyot27** [comment]
Works here.

**Comment by Kein** [comment]
Which version of the FFMS2 avisynth plugin do you use, qyot27?

**Comment by qyot27** [comment]
The latest Git version (or at least within a couple commits of latest), but the important part isn't on FFMS2's side, it's the FFmpeg libs it's linked against.  And I make sure that whenever I build FFMS2, I'm using the latest commit on FFmpeg git at the time.

http://forum.doom9.org/showthread.php?p=1709647#post1709647

**Comment by Kein** [comment]
Okay, this is weird. With installed ffms2 plugin Avisynth no longer returns Version()

**Comment by qyot27** [comment]
Add your plugins/ dir to Windows' %PATH%.

Second, the FFMS2.avsi provided in the 7z is necessary for the ffms2.dll in the 7z to autoload, because it's a C plugin (only relevant for classic AviSynth; AviSynth+ autoloads C plugins).

**Comment by Kein** [comment]
Here is my %PATH%:

>C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Programs\AviSynth\plugins

The thing is - I can open other AVis made with FRAPS or Dxtory (this time LAGS as codec) just fine, but this one don't want to. However, another video recorded with Dxtory codec but in 1024x768 opens just fine.

This literally makes no sense to me.

**Comment by myrsloik** [comment]
This file only works with ffmpeg and not libav from current git. Will probably work in the next release.
