### ISSUE TITLE
Creating an FFMS_AudioSource from multiple tracks possible?

### ISSUE THREAD

**Issue by chartelt** [FFMS/ffms2#195]
My case is a .mov container with separate wav tracks for a 5.1 sound layout.

Currently I create a FFMS_AudioSource for each audiotrack to get the samples one by one. I wonder if I can create an FFMS_AudioSource from more than one audiotrack in a container to avoid this step?

**Comment by dwbuiten** [comment]
This seems quite outside the scope of FFMS2. This is by all means, a corner case, and existing libraries exist to easily merge and/or mix them.

**Comment by tgoyne** [comment]
Is there any sort of metadata that indicates that the separate tracks should be combined? If so combining them automatically and reducing the number of stupid things users have to deal with would be reasonable.

**Comment by dwbuiten** [comment]
AFAIK in many situations it is just assumed, since it's part of some deliverables spec somewhere.

I may be wrong for other cases.

**Comment by chartelt** [comment]
The metadata (or channel layouts) are nicely signaled for each audio track (at least for mov), so I read those and handle the tracks accordingly. I was just wondering if there was an easier way to deal with this inside ffms, but I understand that this is out of scope.
