### ISSUE TITLE
infinite-tracks branch fail build

### ISSUE THREAD

**Issue by sl1pkn07** [FFMS/ffms2#200]
Hi

when build infinite-tracks branch with gcc 5.1.0

http://sl1pkn07.wtf/paste/view/6a63803c

greetings

**Comment by myrsloik** [comment]
Fixed

**Comment by sl1pkn07** [comment]
Hi, nope

the "typedef" is fixed but not the undefined reference

    src/core/.libs/libffms2.so: undefined reference to `ResizerNameToSWSResizer(char const*)'
    collect2: error: ld returned 1 exit status
    Makefile:646: fallo en las instrucciones para el objetivo 'src/index/ffmsindex'
make: *** [src/index/ffmsindex] Error 1

**Comment by myrsloik** [comment]
Fixed again
