### ISSUE TITLE
build-win-deps.sh doesn't actually work with libav

### ISSUE THREAD

**Issue by wrosecrans** [FFMS/ffms2#203]
I am trying to do a windows build, so per the instructions for Windows-specific compilation notes, I ran the build-win-deps.sh, which doesn't seem to be particularly well documented.  It asks if you want to use libav or ffmpeg, and requests that you tell it a toolchain.  It doesn't actually list what the options are for toolchain, I've been using msvc (With VS2013), but it's not immediately obvious how I should phrase using the default msys compiler, since I have to be in an msys shell to run the script.  In any event, I tried to build with libav, but regardless of which library you request, the ffmpeg_common_flags includes    --disable-ffmpeg         --disable-ffplay          --disable-ffprobe          --disable-ffserver      which cause a failure when it tries to ./configure libav since it doesn't have a ffmpeg binary to disable.  It does have a --disable-programs.  The script needs to supply the correct flags to the given configure script.

**Comment by myrsloik** [comment]
I guess it's technically a bug but I also think you should be compiling it with FFmpeg. Libav lost the competition...

**Comment by wrosecrans** [comment]
Ah thanks, that's good to know.  I did ultimately build with ffmpeg instead of libav, but it would be good if it was at least the clear default to use ffmpeg.  Asking the user a question with only one right answer probably isn't ideal.

**Comment by myrsloik** [comment]
Few people ever compile it themselves on windows so it's only really tested around release time. When I compiled it myself I even missed that there is a script to help with it.
