### ISSUE TITLE
Interlaced H264 decoding is still ridiculously broken

### ISSUE THREAD

**Issue by myrsloik** [FFMS/ffms2#206]
No fucks given

**Comment by dwbuiten** [comment]
Is this still a thing?

**Comment by myrsloik** [comment]
I think it's still broken if that's what you mean by a thing

**Comment by dwbuiten** [comment]
I think https://github.com/FFMS/ffms2/pull/315 has fixed this. If it isn't, someone can reopen for file a new bug.
