### ISSUE TITLE
Open MP4/MOV without indexing

### ISSUE THREAD

**Issue by tophf** [FFMS/ffms2#207]
[LSMASHVideoSource()](/VFR-maniac/L-SMASH-Works) can open MP4/MOV files quickly without building the index first (with frame-seeking support), apparently, by reading the file's built-in index. I've been using it for a few years. It'd useful to add such mode to FFMS2 (and, probably, set it as default for mp4/mov).

**Comment by myrsloik** [comment]
For some containers it is kinda possible to do this. I did experiment with this for AVI in the age of ffms1 but in the end decided that the amount of special casing needed isn't worth it. You'll also get much worse results on files with derpy indexes which there's no shortage of...

**Comment by tophf** [comment]
The primary benefit as I see it is to open multi-gigabyte mp4 files (100GB, for example) for lossless encoding pass(es) with a healthy index.

**Comment by myrsloik** [comment]
Your use case is exceptional and since you produce the files yourself you should be able to find an alternative solution that works.

The standard use case for ffms2 is to throw it at any random shit downloaded from the interwebs.

**Comment by tophf** [comment]
`wontfix`?

**Comment by myrsloik** [comment]
Nope, too much work and outside the scope of the project in my opinion. If the goal only was to support a few containers instead of all of them it'd be reasonable.

Patches welcome.
