### ISSUE TITLE
FFMS_GetFrame doesn't work properly with animated gifs

### ISSUE THREAD

**Issue by nixxquality** [FFMS/ffms2#210]
When you call FFMS_GetFrame on an animated gif, it seems you get every frame spliced into one picture:
![example](http://i.imgur.com/y1gEpzE.png)

No sample file should be needed as it happens with every animated gif in my experience.

**Comment by tgoyne** [comment]
I tried opening a few animated gifs that I had lying around and they all worked fine for me.

**Comment by nixxquality** [comment]
My bad, I tried it with a development build dll now and it seems it has been fixed already.
