### ISSUE TITLE
Missing avisynth.h 

### ISSUE THREAD

**Issue by codics** [FFMS/ffms2#214]
Cannot build trunk due to missing header, avisynth.h

```c++
#ifndef FFAVSSOURCES_H
#define FFAVSSOURCES_H

#include <vector>
#include <windows.h>
#include <avisynth.h>
#include "ffms.h"
```

**Comment by myrsloik** [comment]
As you can see there are <> around avisynth.h so you have to find it yourself. You can get the latest header avs+ headers from https://github.com/AviSynth/AviSynthPlus/tree/MT/avs_core/include
which is the recommended version to use

**Comment by codics** [comment]
Got it; an external dependency. Thanks.
