### ISSUE TITLE
Implement support for mid-stream audio channel configuration changes

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#22]
_From [kalle.blomster](https://code.google.com/u/112284474385978317423/) on August 20, 2010 07:46:16_

Currently we support video streams that switch resolutions (can happen in broadcast television, among other things), but there's no similar support for changing audio channel configurations. ffmpeg seems to support it, at least with some codecs, so we should as well.

Some consideration on how to handle this on the API level must be done.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=22_

**Comment by myrsloik** [comment]
Nobody will ever implement this
