### ISSUE TITLE
Wrong keyframes generated by scxvid when using ffms 2.21

### ISSUE THREAD

**Issue by MoodyMoon** [FFMS/ffms2#220]
Tested with Avisynth 2.5.8 and 2.6.0.
Problem started with version 2.21 icl and msvc version. There is no problem with version 2.20.

**Comment by myrsloik** [comment]
Probably fixed in git. Did you try that?

**Comment by MoodyMoon** [comment]
I didn't test using any of the git versions because there are no binaries provided and I have no idea how to compile the source. I will be glad to test it if you have the binaries though. In the mean time, I will just take your word for it and I have been using version 2.20 instead. Thanks for the help.
