### ISSUE TITLE
Missing audio samples at beginnig

### ISSUE THREAD

**Issue by combucha** [FFMS/ffms2#221]
Container MP4 with AVC+AAC LC
If I open thru FFMS2v2.20 and older versions, decoded audio stream has around 54ms of silence (padding of aac, exactly 2624 samples here). I always thought that these samples were discarded during indexing and I'm A/V synced in VirtualDub. It's about containers without any elst atom defining A/V sync (if audio elst atom exist, its value is respected in output audio).
Now the same MP4 opened with FFMS2v.2.21 (and latest RC2) has cutted audio stream at beginning. Looks like improper audio indexing or removing aac padding silence - around 100ms of audio at beginning is absent. 
What causes this issue?

**Comment by slajar** [comment]
Well, those samples are only discard if you select the appropriate delay option. See: https://ffmpegsource.googlecode.com/svn/trunk/doc/ffms2-avisynth.html at "adjustdelay"

**Comment by combucha** [comment]
Will close it since it's no longer actual and cannot reproduce this issue with current version.
It was independent from adjustdelay switch.
