### ISSUE TITLE
Shouldn't PAR be handled automatically?

### ISSUE THREAD

**Issue by Q3CPMA** [FFMS/ffms2#225]
Hello,
I use the Vapoursynth plugin, and when doing `vid = core.ffms2.Source(source='my.mkv')`, it gives me a video that obviously lack the necessary PAR metadata. Shouldn't the scaling be done automatically, since metadata can't be passed easily (or I'm too ignorant to know how to do it)?

Thanks.

**Comment by tgoyne** [comment]
I've never actually used the VapourSynth stuff, but it appears to expose AR information as _SARNum and _SARDen. Automatically applying the AR would be undesirable in a lot of scenarios, but an option to do so sounds handy.

**Comment by Q3CPMA** [comment]
Well, I think VS can only output raw y4m, so I don't think we can pass the metadata, only resize (if we do something). I can just use mkvmerge to change the metadata, though.

**Comment by myrsloik** [comment]
Not a bug. Big operations (which resizing is) should never be implicit in VapourSynth. It's easy to write a python function you can import to automatically adjust it if that's what you need.
