### ISSUE TITLE
Build error since commit c5712e02116b692ef0151c4be07aaddb59c0e728

### ISSUE THREAD

**Issue by 4re** [FFMS/ffms2#230]
Commit c5712e02116b692ef0151c4be07aaddb59c0e728 breaks compilation.
gcc 5.2.0
ffmpeg 2.7.2
[log](https://bpaste.net/show/71c8014287ad)

**Comment by darealshinji** [comment]
Same problem with gcc 4.8.4 and latest ffmpeg git snapshot.
