### ISSUE TITLE
Revert numthread use...

### ISSUE THREAD

**Issue by komisar666** [FFMS/ffms2#232]
is it possible to revert use of "numthread"?

simple discussion http://stackoverflow.com/questions/13212342/whats-the-difference-between-thread-posixs-and-thread-win32-in-gcc-port-of-windo

another discussion http://stackoverflow.com/questions/17242516/mingw-w64-threads-posix-vs-win32

patch http://komisar.gin.by/x.patch/no_c++11_threads.diff

maybe configure may detect this issue?

**Comment by dubhater** [comment]
Why? Have you considered compiling your GCC with POSIX threads?

**Comment by komisar666** [comment]
No. My toolchain compiled with Win32 threading model...

**Comment by dubhater** [comment]
Too bad?

**Comment by komisar666** [comment]
Why configure dont detect this issue? Maybe this is a better solution?
