### ISSUE TITLE
__imp_XXXXXX with static build...

### ISSUE THREAD

**Issue by komisar666** [FFMS/ffms2#233]
exact describe in this post http://forum.doom9.org/showthread.php?p=1738744#post1738744

**Comment by dwbuiten** [comment]
Is this fixed by https://github.com/FFMS/ffms2/commit/06bcf231cab00bfbf28f910c6ec3ca6680957cb6?

**Comment by tgoyne** [comment]
There's no actual build system support for it, but I guess you could manually add FFMS_STATIC to CPPFLAGS while building ffms2.
