### ISSUE TITLE
'ffmsindex.exe' @VirusTotal => 19/55 (false?) positives!

### ISSUE THREAD

**Issue by krassle** [FFMS/ffms2#235]
Major AntiVirus software(*AVG*, *Avast*, *Avira*, *Bitdefender*, *F-Secure*, *GData*, *McAfee*,...) detects _ffmsindex.exe_ as a malware/trojan @[VirusTotal] (https://www.virustotal.com/en/file/af42e338285477302b93243331873fd21185126883fdbd2b2472c663c1f6e486/analysis/1446121470/). Therefore possible complains on install/upgrade.

**Comment by slajar** [comment]
Well, nobody here can do anything neighter against false positives nor infected files.
