### ISSUE TITLE
FRAPS videos cause violent crashing

### ISSUE THREAD

**Issue by nixxquality** [FFMS/ffms2#236]
I was given [this sample file](https://gitgud.io/nixx/WebMConverter/uploads/1b174cdfa43ad4e8572e67a5a114c8b3/XR_3DA_2015-10-11_19-53-06-71.avi) as an example.
In my program using the C API, FFMS_GetFrame crashes the entire thing.

Even when trying to view it in a simple avisynth script, it causes avspmod to freak out and I am otherwise unable to watch the clip.

I think this is a regression introduced recently in FFMS2, as Fraps has not been updated recently. Most likely introduced between 2.21 and 2.22.

**Comment by dwbuiten** [comment]
Works perfectly fine here with FFMS2 HEAD and FFmpeg HEAD. Sounds like whatever version of FFmpeg/Libav it was linked against had a bunch, which is fixed currently.

**Comment by nixxquality** [comment]
Good to hear.
