### ISSUE TITLE
AudioSource caching doesn't work always correctly

### ISSUE THREAD

**Issue by slajar** [FFMS/ffms2#238]
I found that there was a change in July at AudioSource for the caching stuff. This seems to underflow an unsigned int under some circumstances. I fixed it for me like that: 

https://github.com/FFMS/ffms2/commit/929e4507f9851cb250a1b6678b11f0ddf7a4c90c#commitcomment-14148640

Actually, I don't fully understand the caching mechanism to provide a real patch. Either some one explains the caching to me (so I can write a patch) or some one fixes the "right" way.

**Comment by tgoyne** [comment]
Can you upload a sample that hits this? It should only happen if there's a bug elsewhere or the source is fucked in some way, and if it's the former I'd prefer to fix that.

**Comment by slajar** [comment]
Don't care about this anymore. I found that this is a rare bug with a divx encoded AVI. I have never seen the crash at this point in ffms2 anymore. I'll close that issue.
