### ISSUE TITLE
FFCopyrightInfringement broken after moving it to C++

### ISSUE THREAD

**Issue by kuukunen** [FFMS/ffms2#239]
The commit https://github.com/FFMS/ffms2/commit/817be40c01bb8798c3b1c334d3aa138dede31075
changed it from AudioDubEx(FFVideoSource, FFAudioSource) to just FFvideoSource

**Comment by myrsloik** [comment]
This is a most horrible oversight. I'll make sure to fix it immediately.

**Comment by myrsloik** [comment]
Should be fixed now. Didn't really test it though.
