### ISSUE TITLE
"Source: No video track found" with latest ffmpeg and ffms2

### ISSUE THREAD

**Issue by Kagami** [FFMS/ffms2#246]
I get `vapoursynth.Error: Source: No video track found` when trying to read any file with latest ffms2 (https://github.com/FFMS/ffms2/commit/ce78301afc8ff47cd3f3235637e2115511996500), ffmpeg (https://github.com/FFmpeg/FFmpeg/commit/4c5136a48ba8beb7737a0b67d4d4f64add1263a9) and vapoursynth (https://github.com/vapoursynth/vapoursynth/commit/9080b2e5bf0a5dfc1abdd616d55cebf3904b03d6).

Version 2.22 works fine with latest ffmpeg, so I suppose this is probably related to ffms2. Let me know if you need some more debug info, I'm not sure what might be useful. Note that you need to remove old `ffindex` files when trying to reproduce this.

**Comment by dwbuiten** [comment]
When you say 'any file', which formats specifically did you test?

**Comment by Kagami** [comment]
MKV+H264, Y4M. Version 2.22 opens them just fine.

**Comment by dwbuiten** [comment]
Thanks. I works for some other formats, actually. I'll take a look.

**Comment by dwbuiten** [comment]
If possible, could you test your files with the PR I have sent above?

**Comment by Kagami** [comment]
Since @myrsloik already merged it, I rebuilt master and now it works for abovementioned files. Thanks!
