### ISSUE TITLE
Question about VSHelper.h and VapourSynth.h in ffms2/src/vapoursynth

### ISSUE THREAD

**Issue by sl1pkn07** [FFMS/ffms2#248]
Hi

No need synconize VSHelper.h and VapourSynth.h in ffms2/src/vapoursynth with the sources on Vapoursynth project?

Greetings

**Comment by myrsloik** [comment]
No. You only need newer headers to use new parts of the API (nothing relevant to ffms2 or 98% of all other plugins has been added since the first version).
