### ISSUE TITLE
Add image series support

### ISSUE THREAD

**Issue by myrsloik** [FFMS/ffms2#250]
Opening multiple files by using file%03d.png should be fairly easy to add support for. Just change a huge pile of checks that think there's only one input file.

**Comment by wrosecrans** [comment]
I saw this issue got closed.  Did this get closed as "won't fix" or "completed" ?  I don't see anything announcing the new feature, so I am guessing it's been decided against?

**Comment by myrsloik** [comment]
Won't fix-ish. It doesn't belong in ffms2 since it doesn't need indexing. But I have plans to make something ffmpeg based that can read images... some day.
