### ISSUE TITLE
There's no function named FFxxx, v2.22

### ISSUE THREAD

**Issue by Zheitk** [FFMS/ffms2#255]
Hello, I'm using windows xp and just updated from 2.19.2 to 2.22, and It is not recognizing any function at all. I just copied  all the files in the x86 folder, also the .avsi file. Everything works with v2.19.2 and v2.21

**Comment by dwbuiten** [comment]
It could simply be that the toolchain used for 2.22 no longer supports XP, since it is EOL. I don't think you'll find much support, if that's the case.
