### ISSUE TITLE
FFMS2 don't open video when compiled with last FFMpeg from git

### ISSUE THREAD

**Issue by Abs62** [FFMS/ffms2#256]
FFMS2 don't open video when compiled with last FFMpeg from git - "Could not allocate dummy frame" error. It seems it is after commit 0eb4092c1bf4d74c3b9a65fb0dbe4f90d3a316d0 in FFMpeg (14.02.2016). If to change alignment from 1 to 4 in av_image_alloc() calling in the FFMS_VideoSource constructor, no more error, video opened.

**Comment by dwbuiten** [comment]
Does this happen for all videos or just some videos?

The *only* reason I can see this happening is if the video has a palette.

See: https://github.com/FFmpeg/FFmpeg/blob/b4018544fbbcb3581d31866d82bc7f8ff3da4b2a/libavutil/imgutils.c#L218-L224

@myrsloik / @tgoyne does FFMS2 even support palette images?

**Comment by Abs62** [comment]
This calling of av_image_alloc() is not related to video format, function called with FFMS_PIX_FMT(GRAY8) format parameter.

**Comment by dwbuiten** [comment]
Oh, it seems you're right .FFmpeg made an silent API break. Lovely. Will fix it.
