### ISSUE TITLE
Problem build with Msys2

### ISSUE THREAD

**Issue by rotd** [FFMS/ffms2#260]
I build FFMS with Msys2 in Mingw64 shell. Its required Libstdc++.dll, both config --enable-shared and --enable-static. 

I try to used config LDFLAGS="-static-libstdc++" (or CXXFLAGS="-static-libstdc++"). Its working with --enabe-static, and building FFmsindex.exe, but not working with --enable-shared (still required libstdc++).

What can i do to build ffms2 with static libstdc++ and shared ffms2.dll to use Avisynth?

Thanks!

**Comment by myrsloik** [comment]
Compile ffmpeg with visual studio like we do, saves a lot of trouble later when linking.
