### ISSUE TITLE
Release-Download of Windows-Build blocked by Chrome

### ISSUE THREAD

**Issue by sschnug** [FFMS/ffms2#261]
Just to give you a heads up:

Default Chrome blocks the download of [release link](https://github.com/FFMS/ffms2/releases/download/2.22/ffms2-2.22-msvc.7z).

Not sure what needs to be done to address this. Maybe some users might be annoyed by this.

**Comment by dwbuiten** [comment]
That's pretty... wtf

**Comment by myrsloik** [comment]
It's done that for a very long time. No idea why it's considered so malicious.
