### ISSUE TITLE
FFMS2 v2.22 doesn't work when trying to extract audio from multi-AC3 VOB file ("No audio track found")

### ISSUE THREAD

**Issue by unv-unv** [FFMS/ffms2#263]
FFMS2 v2.22 doesn't work when trying to extract audio from multi-AC3 VOB file.

Test file: https://drive.google.com/file/d/0BxITyeHd2HuMQjNmSjhuZHBDTG8/view?usp=sharing
(this is a part of "Man of La Mancha" DVD movie containing "The Impossible Dream" song by Don Quixote).

This 1GB VOB file contains 5 audio streams (AC3, 48 kHz) and 9 subtitle streams. It is normally played by Media Player Classic from latest K-Lite Codec Pack (allowing selecting any audio/subtitle stream).

Tried several script variants, all returning error `"FFAudioSource: No audio track found (FFMS2.avsi, line 40)"`:

1) Calling FFMpegSource2 (with audio autoselect):

`file = "VTS_01_5.VOB"`
`video = FFMpegSource2(file, atrack=-1)`
`video`

2) Calling FFAudioSource explicitly:

`file = "VTS_01_5.VOB"`
`audio = FFAudioSource(file, track=-1)`
`video = FFVideoSource(file)`
`video = AudioDub(video, audio)`
`video`

3) Calling FFIndex first:

`file = "VTS_01_5.VOB"`
`FFIndex(file)`
`video = FFMpegSource2(file, atrack=-1)`
`video`

Of course, I deleted `VTS_01_5.VOB.ffindex` file before each run. No effect.

I tried several versions of FFMS2: 2.22, 2.21, 2.20, 2.19 (copying `FFMS2.avsi`, `ffms2.dll`, `ffms2.lib`, `ffmsindex.exe` from x86 folder into AviSynth plugin folder and deleting `.ffindex` file after each downgrade) - not working in any version.

Also I tried manually specifying atrack (1, 2, 3, 4, 5). In this case another error message was returned: `"FFAudioSource: Audio track contains no audio frames (FFMS2.avsi, line 40)"`.

Also I tried manually specifying atrack from subtitles track range (6, 7, 8, 9, 10, 11, 12, 13, 14, 15 - subtitles tracks and video). Then it logically returned error `"FFAudioSource: Not an audio track (FFMS2.avsi, line 40)"`.

And finally I tried to specify track out of range (16). And the error was `"FFAudioSource: Out of bounds track index selected (FFMS2.avsi, line 40)"`.

When opening file with audio track disabled (atrack=-2), it opens OK (but, of course, without audio).

So it proves that the file contains 5 audio tracks (numbered from 1 to 5) but they're somehow not recognized by FFMS2 of the latest version. Could you please fix it?

**Comment by myrsloik** [comment]
Seems to work in the latest build. Try this one: https://dl.dropboxusercontent.com/u/73468194/ffms2-2016-10-10.7z
