### ISSUE TITLE
2.20 doesn't normalize framerate

### ISSUE THREAD

**Issue by MonoS** [FFMS/ffms2#264]
I kindly ask a build of the 2.20 version with the framerate normalization commit b9fd843 .

I know that it's a pretty ancient version, but is the only one i'm pretty confident that wont give me the frame duplication bug i saw with newer version.

Thanks for the attention

**Comment by myrsloik** [comment]
Report the frame duplication issue instead

**Comment by MonoS** [comment]
I would, but i'm unable to reproduce the issue in the current version. It used to happen at random clip at random frames when using mvtools [maybe non linear access] or other similar filter.
I used to have a clip that reproduced consistently the issue but after a vs version it didn't anymore.
I can't report a bug i can't reproduce anymore for some obscure reason and without test clips or i had already done that, and finding a clip which have this issues is very time consuming between encoding and watching the clip.
With version 2.20 i am 100% sure i don't get the bug
