### ISSUE TITLE
Video output is green and upside down when using 2.22 but fine on 2.21

### ISSUE THREAD

**Issue by rstarkov** [FFMS/ffms2#271]
The [attached file](https://github.com/FFMS/ffms2/files/501102/repro.mp4.zip) reproduces the problem. Just go `FFVideoSource("repro.mp4")` and it should be green and upside down when using the msvc 2.22 build. I'm using the 32-bit build with AviSynth 2.60.

This file was produced by ffmpeg.exe version N-74835-gbd6610c using libx264 as the video encoder.

**Comment by myrsloik** [comment]
Works in my most recent compile from master. So it'll work in 2.23 I guess.
