### ISSUE TITLE
[ffmsindex] Progress info is overwritten by later messages

### ISSUE THREAD

**Issue by Coacher** [FFMS/ffms2#274]
Hello.

If I do `ffmsindex <FILE>`, I get the output:
```
Writing index... done... 100%
```

If I do `ffmsindex -c -k <FILE>`, I get the output:
```
Writing timecodes... done.00%
Writing keyframes... done.
Writing index... done.
```

Note that in both cases progress info (`Indexing, please wait... XX%`) is overwritten, which results in semi-meaningful output esp. in the second case.

Please fix ffmsindex to keep progress info and `Writing ...` messages on separate lines.

**Comment by myrsloik** [comment]
OS?
FFMS2 version?

**Comment by Coacher** [comment]
OS Gentoo amd64.
FFMS2-2.23.

**Comment by myrsloik** [comment]
Fixed in ffms2000 branch
