### ISSUE TITLE
SWScale is a steaming pile of shit and should be replaced

### ISSUE THREAD

**Issue by myrsloik** [FFMS/ffms2#277]
Can't convert to planar RGB
Greenish tint
Clever code

The list goes on. We should replace it as it still causes several bugs and unsupported cases.

**Comment by pat357** [comment]
I think something like ZIMG could do wonders here.

**Comment by myrsloik** [comment]
Yes, it could, but there are some exotic corner cases an pack/unpack that's just too boring to write.

**Comment by myrsloik** [comment]
Too much effort, easier to simply apply zimg right after.
