### ISSUE TITLE
ffms2.dll is not an AviSynth 2.5 plugin

### ISSUE THREAD

**Issue by eallik** [FFMS/ffms2#278]
I'm on 64bit Windows 10, installed the latest AviSynth 2.5, downloaded the latest [ffms2](https://github.com/FFMS/ffms2/releases/tag/2.23), however I cannot load the DLL as a plugin.

my script does this:

    LoadPlugin("C:\Program Files (x86)\AviSynth 2.5\plugins\ffms2.dll")

also tried loading from the same directory as the script to no avail:

    LoadPlugin("ffms2.dll")

the error message I get is:

    Plugin C:\Program Files (x86)\AviSynth 2.5\plugins\ffms2.dll is not an AviSynth 2.5 plugin

**Comment by myrsloik** [comment]
It's a 2.6 plugin.

**Comment by eallik** [comment]
yes, you're right — I thought I'd downloaded 2.6 but apparently I had 2.5 installed instead. apologies!
