### ISSUE TITLE
2.23.1 can't read PNG format

### ISSUE THREAD

**Issue by k24w24** [FFMS/ffms2#279]
2.23 is good.
but 2.23.1 can't  make clip from PNG.

**Comment by myrsloik** [comment]
sample file

**Comment by k24w24** [comment]
Do it.

    보더리스 = c.ffms2.Source(
        source=파일명,
        fpsnum=60,
        format=vs.RGB24,
        cache=False
    )[0]

![245](https://cloud.githubusercontent.com/assets/24914118/22160151/7cb3d2da-df87-11e6-818f-8ec918a719ad.png)

**Comment by myrsloik** [comment]
Will be fixed in the next release, I forgot to compile it with zlib
