### ISSUE TITLE
BluRay m2ts freeze/out of order frames at the start

### ISSUE THREAD

**Issue by sneaker2** [FFMS/ffms2#280]
Hi,

I got a sample from BluRay that has problems when opened using ffvideosource() (2.23.1). The second frame is out-of-order and freezes for some ~10 frames. Works fine in players like MPC-HC/LAV, lwlibavvideosource() or simply ffmpeg.

https://www.sendspace.com/file/te146n
(10s_VIDEO_SOURCE.m2ts)

**Comment by myrsloik** [comment]
This happens with earlier versions too, right?=

**Comment by sneaker2** [comment]
Yes. 2.23 and 2.22 seem to behave identical to 2.23.1. 2.21 seems to work with linear access but has the same error when stepping back. 2.20 similarly to >=2.22, except even the very first frame is wrong.

2.19 seems ok.

**Comment by myrsloik** [comment]
Try ffms2000 test5

**Comment by sneaker2** [comment]
Yes, look fixed.

Interestingly, only the .ffindex file matters. If created using test5 even test4 will play correctly. Or vice versa: created by test4 and test5 will play incorrectly as well.

**Comment by myrsloik** [comment]
Yes, the key is in the index.
