### ISSUE TITLE
Cannot build ffms2 as a shared library

### ISSUE THREAD

**Issue by jasonMisaq** [FFMS/ffms2#281]
I am building ffms2 on Fedora 25 (x86_64). After I installed libav dependencies for the ffms2 `configure` file, it now complains that it cannot build ffms2 as a shared library:   
```
configure: error: in `/home/john/src/ffms2':
configure: error: cannot build ffms2 as a shared library
See `config.log' for more detail
```
[Here](http://pastebin.com/5sfsAXjt) is the complete output. I don't understand what it means and what I should do. I tried using `--enable-shared` flag for `configure`, but still with no success and received the same error.

**Comment by raberto-nowhere** [comment]
Same issue here and also i use --enable-pic when i configured ffmpeg. I don't understand how to fix this as well. I am using the last commit ca5ef92169c43883533c95eae60981155c22979e  which build passed.

**Comment by dwbuiten** [comment]
We need a cop of your `config.log` in order to see what's going on. Can you attach it?

**Comment by jasonMisaq** [comment]
@dwbuiten here is my config.log output:   http://pastebin.com/ep3nkbsp, I hope it helps

**Comment by kblomster** [comment]
Are you sure you configured ffmpeg with --enable-pic? If yes, have you tried building it as a shared library instead of a static one?
