### ISSUE TITLE
convert to RGB24 has problem

### ISSUE THREAD

**Issue by k24w24** [FFMS/ffms2#283]
![screen-2017-02-03_16-55-46](https://cloud.githubusercontent.com/assets/24914118/22583812/3a21bc2e-ea32-11e6-8a88-e22f6059b1d2.png)

** **
# fmtc has no problem.

yuv444 = c.ffms2.Source(
    cache=False,
    source="same.jpg",
    fpsnum=60
)[0] * 100

yuv444 = yuv444.fmtc.resample(css="444")
yuv444 = yuv444.fmtc.matrix(mat="601", col_fam=vs.RGB)
yuv444 = yuv444.fmtc.bitdepth(bits=8)

yuv444.set_output()

** **
# but ffms2 has problem.

yuv444 = c.ffms2.Source(
    cache=False,
    source="same.jpg",
    fpsnum=60
)[0] * 100

by_ffms2 = yuv444.resize.Point(
    format=vs.RGB24,
    matrix_s="709"
)

yuv444.set_output()
# Resize error 1026: RGB color family cannot have YUV matrix coefficients

** **
# same..

rgb24 = c.ffms2.Source(
    cache=False,
    source="same.jpg",
    fpsnum=60,
    format=vs.RGB24
)[0] * 100

rgb24.set_output()
# Resize error 1026: RGB color family cannot have YUV matrix coefficients

**Comment by myrsloik** [comment]
This is example is invalid usage, you can't have matrix_s refers to the output matrix and you can't have a YUV matrix for RGB. Did you really mean matrix_in_s? That'd be a different thing.

yuv444 = c.ffms2.Source(
cache=False,
source="same.jpg",
fpsnum=60
)[0] * 100

by_ffms2 = yuv444.resize.Point(
format=vs.RGB24,
matrix_s="709"
)

yuv444.set_output()

**Comment by myrsloik** [comment]
The other case is a real bug and I'll try to fix it

**Comment by myrsloik** [comment]
Fixed in ffms2000 branch, try out test2 once it's available.
