### ISSUE TITLE
RGB images are marked as "limited" range

### ISSUE THREAD

**Issue by madshi** [FFMS/ffms2#292]
When loading RGB images (e.g. a BMP file), ffms2 marks the image to have a "limited" range (16-235) via metadata. This is a bad decision, IMHO, because usually BMP, PNG and JPG files are full range.

If you want to set range metadata for bitmap images, I think you should set full range. Otherwise, at least leave the range unspecified.

Just my 2 cents, of course.

**Comment by myrsloik** [comment]
You didn't force any output format or colorspace, right? I just fixed a pile of issues with that...

**Comment by madshi** [comment]
Not that I'm aware of. My script looks like this:

```
import vapoursynth as vs
core = vs.get_core()
video = core.ffms2.Source(source='castle.bmp')
video = core.madVR.Process(video, some parameters)
video.set_output()
```

**Comment by myrsloik** [comment]
Death by a thousand horrible format guesses

**Comment by myrsloik** [comment]
Should be fixed now, verify it in the next test

**Comment by madshi** [comment]
Thanks.
