### ISSUE TITLE
Loading mov files which reference to external files

### ISSUE THREAD

**Issue by Selur** [FFMS/ffms2#306]
FFmpeg supports reading mov reference files through:
-enable_drefs 1 -use_absolute_path 1
would be nice if this could be supported in ffms2.
Sample for such a mov is linked over at: https://forum.selur.net/showthread.php?tid=162
(got a copy of it so can also upload it to my own google drive in case it goes down)

Cu Selur

Ps.: posted it also into the Vapoursynth issue tracker 2 weeks ago (https://github.com/vapoursynth/vapoursynth/issues/343)

**Comment by myrsloik** [comment]
After som deliberations we've reached the conclusion that it's a horrible idea and better implemented as a playlist wrapper plugin or something similar
