### ISSUE TITLE
Remove colorspace/transfer/other constants

### ISSUE THREAD

**Issue by myrsloik** [FFMS/ffms2#308]
Remove all constants that are copied from ffmpeg headers directly and come from some iso standard.

**Comment by myrsloik** [comment]
These enums are simply copied from the iso standard and can be safely removed:
FFMS_ColorPrimaries
FFMS_TransferCharacteristic
FFMS_ColorSpaces

These enums haven't had any observable effect for a long time and are deprecated:
FFMS_Sources
FFMS_CPUFeatures

**Comment by kodabb** [comment]
> Remove all constants that are copied from ffmpeg headers directly and come from some iso standard.
👍

**Comment by kodabb** [comment]
you could probably drop ColorRanges ChromaLocations too
c6f9e4dc2571c45d9397051e0ff31432dc09fa46
