### ISSUE TITLE
Audio distorted with XDCAM HD playback 24bit audio

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#31]
_From [eyeperfect](https://code.google.com/u/100434052458930270625/) on November 05, 2010 07:10:04_

What steps will reproduce the problem? 1. Create Avisynth file
LoadPlugin("C:\Program Files (x86)\AviSynth 2.5\ffmpegsource-2.14-mt\ffms2.dll")
#LoadPlugin("C:\Program Files (x86)\AviSynth 2.5\FFmpegSource-1.21\FFMpegSource.dll")
source="\\kv1.medialaan.vmma.be\KV1ToAvid\C0044.mxf"

#volgend werkt!
FFIndex(source,cachefile = source + ".ffindex", errorhandling=1)

vid = FFVideoSource(source,cache=true,seekmode=1,cachefile=source +".ffindex")
snd = FFAudioSource(source,cache=true,cachefile=source + ".ffindex")

stereo = GetChannel(snd, 1)

a1 = audiodub(vid, stereo)

a2 = Subtitle(a1, "hier is mijn ondertitel", first_frame=25, last_frame=100, align=5, y=560, font="Arial", size=35, text_color=$eeeeee) 

a3 = ShowSMPTE(a2, offset="01:00:00:00", x=160, y=76, font="Arial", size=29,text_color=$14942E)

return a2

2. Playback with graphedt
3. Sound is distorted What is the expected output? What do you see instead? You hear bad sound What version of the product are you using? On what operating system? Avisynth 2.5, ffmpegsource 2.14

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=31_

**Comment by myrsloik** [comment]
Works now
