### ISSUE TITLE
expand VideoProperties with HDR metadata

### ISSUE THREAD

**Issue by kodabb** [FFMS/ffms2#310]
The current HDR metadata exported by libavcodec and libavformat is commonly called "static metadata" since it's not supposed to change per frame. It is not uncommon that this data is present in the first frames of a video sequence and then never exported again.

On the ffms side, this means that it becomes available only after the first call to `FFMS_GetFrame()`, but it would be nice if instead it was provided after opening the decoder, at `FFMS_GetVideoProperties()`: this would allow to have all properties already available before opening an encoder, which usually do not support reconfiguring color properties.

See also https://mailman.videolan.org/pipermail/x265-devel/2018-January/011560.html as example where this would be useful

**Comment by myrsloik** [comment]
Interesting, shouldn't be that hard to do since the first frame is always decoded on opening anyway. I think I did that because even things like format and resolution are (were?) too unreliable.
Exactly which fields need to be exported and from where?

**Comment by kodabb** [comment]
well all the recently added properties in https://github.com/FFMS/ffms2/blob/2625f434dd6d9265152c031e06dd05b5b63c3749/include/ffms.h#L379-L390 would need an equivalent in VideoProps

**Comment by myrsloik** [comment]
I did think about this a bit more. Copying all of that information from the first frame is easy. But why is simply getting the first frame (which will already be decoded as part of creating FFMS_VideoSource) a problem? I kinda understand why it'd be slightly more practical sometimes but is inspecting the first frame really a problem?

**Comment by kodabb** [comment]
well no, but that could be said basically of all FFMS_VideoProperties.
Moreover some fields are already exported because of encoder shortcomings (ie `Stereo3DType`)...

**Comment by myrsloik** [comment]
Point taken, I'll move it. Will the frame properties be completely useless then so I should mark them as deprecated?

**Comment by kodabb** [comment]
it depends how closely you want to mimic ffmpeg API: they are bundled in AVFrame so it makes sense to have them in FFMS_Frame, however it's true they are duplicate
since they're already in, you might as well leave them, maybe when ffmpeg gets proper Dynamic Metadata support we can revisit

**Comment by myrsloik** [comment]
Done I guess

**Comment by kodabb** [comment]
84a06455d530028758a99f84e108ebe38661568f looks good, thanks
