### ISSUE TITLE
Difference between 2.23 and 2.23.1?

### ISSUE THREAD

**Issue by ilovezfs** [FFMS/ffms2#313]
Repology is showing a bunch of the package managers as having an outdated version of ffms2 https://repology.org/metapackage/ffms2/versions because they have 2.23 not 2.23.1. What is the difference between these versions? As far as I can tell they're actually the same thing. How do you want the version displayed to users?

**Comment by myrsloik** [comment]
The .1 was a release made mostly for the windows binaries to have a more recent ffmpeg. I don't tgink there's any other difference between them so call it whatever you want.
