### ISSUE TITLE
how to make ffms2 act like ffmpeg ( command )

### ISSUE THREAD

**Issue by Er-rchydy** [FFMS/ffms2#314]
I'm wondering if i can make `ffms2` act like `ffmpeg`, my current `ffmpeg` command is like this : 
`ffmpeg -i http://site.com:9000/live/xxx.ts -c:v libx264 -c:a  copy -start_number 0 -hls_time 30 -hls_list_size 0 -f hls manifest.m3u8 `
But it crush sometimes, so i'm wondering if i can do something like this from terminal:
`ffms2 -i http://site.com:9000/live/xxx.ts -c:v libx264 -c:a  copy -start_number 0 -hls_time 30 -hls_list_size 0 -f hls manifest.m3u8 `
I read the docs but i didn't understand it.
the operating system is `Centos7`, i'm a beginner so if there is a way to make it like above please show me how , thanks

**Comment by dwbuiten** [comment]
FFMS2 is an indexing and decoding C library and set of plugins for AVISynth/VapourSynth, not a CLI tool, and also includes no encoding or streaming functionality. FFMS2 is likely not what you want.
