### ISSUE TITLE
Re-Visit VP9

### ISSUE THREAD

**Issue by dwbuiten** [FFMS/ffms2#319]
Our parser is now incorrect as of https://github.com/FFmpeg/FFmpeg/commit/0c162854c1fa2a1e43ce5588b67842675f45e3c7.

For versions before `0c162854c1fa2a1e43ce5588b67842675f45e3c7`, we need to keep `ParseVP9`, but for versions after, it is incorrect: It marks any superframes as invisible, because they contain both a visible and invisible frame. There of course was no version bump at all of this breaking change.

Furthermore, the way we are calling `avcodec_send_packet` and `avcodec_receieve_frame`, while correct according the libavcodec documentation, is not correct in pratice, because apparently when the VP9 sueprframe bistream filter is inserted internally (completely hidden from us, this is internal to avcodec), it doesn't seem to properly buffer the full superframe packet. So if we do as we currently do, and call `avcodec_send_packet()` followed by `avcodec_receive_frame()` until we get a frame output, it will lead to silent corruption of the output frame, since the whole superframe packet is not being consumed. According to @wm4, this *should* work, but instead, as a workaround, we should be able call `avcodec_receive_frame()` in a loop (in practice, just a second time), until it returns `AVERROR(EAGAIN)`, rather than stopping when we get a frame.

**Comment by dwbuiten** [comment]
This also means it will now be impossible to support incorrectly muxed VP9 WebM files that had the superframe packets physically split in the file, sort of writing a full parser to find out if we have a merged or split packet, AFAIK.

**Comment by wm4** [comment]
> This also means it will now be impossible to support incorrectly muxed VP9 WebM files that had the superframe packets physically split in the file, sort of writing a full parser to find out if we have a merged or split packet, AFAIK.

The merge BSF is still reachable via public API. Of course that's probably still rather unpleasant to add to your code.

**Comment by dwbuiten** [comment]
> The merge BSF is still reachable via public API. Of course that's probably still rather unpleasant to add to your code.

Is the idea to always run the merge BSF on VP9 streams, and it would be a no-op on properly muxed streams?

**Comment by wm4** [comment]
Yes. The decoder would split it again, as usual. I haven't tried it myself... you can ask BBB whether use of it is sane.

**Comment by dwbuiten** [comment]
Need to get around to fixing up #323... it's needed for AV1 too, now.
