### ISSUE TITLE
can't play some normal media file

### ISSUE THREAD

**Issue by andrewmabc** [FFMS/ffms2#325]
Hi,

I use the latest plugin, but fail to play some media files, such as avi, mp4 and wmv.

I think, 'FFmpegSource can Decodes all ffmpeg (libavcodec) supported A/V formats with frame accurate seeking in AVI, MKV and MP4. See discussion.' according to the link of 'http://avisynth.nl/index.php/External_filters'.

But Why can't I play those normal media files?

Thanks

Regards

Andrew

**Comment by dwbuiten** [comment]
1. Where did you get the plugin binary?
2. What is a 'normal media file'
3. How did you test it?
4. Can you provide a sample of a failing file?

**Comment by andrewmabc** [comment]
1. Where did you get the plugin binary?

I download 'ffms2-2.23.1-msvc.7z' from 'https://github.com/FFMS/ffms2/releases/download/2.23/ffms2-2.23.1-msvc.7z', and copy 'ffms2-2.23.1-msvc\x86\ffms2.dll' and 'ffms2-2.23.1-msvc\FFMS2.avsi' to 'C:\Program Files (x86)\AviSynth\plugins'

2. What is a 'normal media file'
4. Can you provide a sample of a failing file?

split.avi : https://drive.google.com/open?id=1880Wb__p-bPrZyhGkZ81BDzDRbpsaya_

Flowers_and_Trees_1932.avi : https://drive.google.com/open?id=15LFZiqjobPPumbm6Rw4iVfXu-dXuDF3Q

split.avi can be played by FFmpegSource2, while Flowers_and_Trees_1932.avi can't.

3. How did you test it?

I create avs file, in which text is like 'FFmpegSource2("D:\split.avi")' or 'FFmpegSource2("D:\Flowers_and_Trees_1932.avi")'

**Comment by dwbuiten** [comment]
Looks like both file work with FFMS2 HEAD. If you wait a day or two, I can upload a Windows build from git, or you can build it yourself. I'm going to close this bug for now, since it is fixed in HEAD, but I'll update it with a build later, if needed.
