### ISSUE TITLE
Clarification on multithreading

### ISSUE THREAD

**Issue by wrosecrans** [FFMS/ffms2#328]
The API docs note, "FFMS2's video frame and audio sample retrieval functions are not threadsafe; you may only have one request going at a time."

Does that mean that you can only have one thing happening globally?  Or does it mean that you could get away with only having one request happening at a time on any given file?  I.e.  Could I have two threads doing different things in unrelated files at the same time?

Is there any plan to revisit the design choices that make concurrent access to one piece of media impossible?  I am working on a real time playback thing, and the API is sooooooooo much nicer and friendlier than trying to muck around with raw FFMPEG, but it would simplify some of my own design if it were easy to have one thread doing video and one thread doing audio concurrently.

**Comment by tgoyne** [comment]
There's no global state other than the things done by `FFMS_Init()`. Opening the same file on two different threads at once is fine; you simply can't open the file once and use the index/videosource/audiosource/etc. objects from multiple threads.
