### ISSUE TITLE
Support loading segmented files

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#33]
_From [kalle.blomster](https://code.google.com/u/112284474385978317423/) on November 17, 2010 02:06:35_

It would be nice if FFMS could fake multiple files being one file, especially for VOB's and the like. This probably requires some substantial work as well as some API breakage.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=33_

**Comment by myrsloik** [comment]
No point

**Comment by theworm4002** [comment]
would have been nice to see that fixed. any reason it was not? to me, "No point" makes no sense. I mean, of course, there is. but what do I know.
