### ISSUE TITLE
building with msvc

### ISSUE THREAD

**Issue by shekh** [FFMS/ffms2#335]
Hi,

ffms2-api.md:
> To build everything with VC++, run build-win-deps.sh from a msys shell to build all of the dependencies

Where is this file? What it supposed to do?

**Comment by dwbuiten** [comment]
This is a case of outdated documentation, I'll fix it. That file no longer exists, and isn't needed.

**Comment by MinorMole** [comment]
If someone builds the latest of the ffms2 for Avisynth, please share it with me. 😄
