### ISSUE TITLE
libffms2-4 on Ubuntu with VapourSynth returns two VideoNode objects with the format argument

### ISSUE THREAD

**Issue by marksfink** [FFMS/ffms2#341]
I'm running Ubuntu 18.10.  I installed the libffms2-4 package provided by apt.  And I installed the vapoursynth packages from apt also.

If I use this line in a VPY script, all is well:
video = core.ffms2.Source(source)

If I add the format argument, I have problems.  As in:
video = core.ffms2.Source(source, format=vs.YUV420P8)

And I see the problem with any format specified.  The problem arises simply by adding the format argument.

The problem is that ffms2 returns a list of two VideoNode objects.  So I have to add this line for subsequent commands to work:
video = video[0]

The two objects that it returns are identical, so I could use either one, but that's beside the point.

I also have VapourSynth and ffms2 installed on a Windows machine and I do not see the problem there.

I attached debugger output from VS Code so you can see what I mean.

![vscode](https://user-images.githubusercontent.com/37458589/51441127-4f27e000-1c9c-11e9-9efb-6e64a0a33d72.png)

**Comment by myrsloik** [comment]
Miscompilation?
