### ISSUE TITLE
audiosource not support for vfr audio frames

### ISSUE THREAD

**Issue by yinhanng** [FFMS/ffms2#347]
FFMS_AudioSource base on samplestart  to locate the audio data,
but i meet one media file , two close by audiopacket , dts jumps a lot as next

dst_time   duration  
30.688033   2880
30.720033   2880
30.752033   285121
33.920044   2880
33.952044   2880

below case would cause audio not async with video, would ffms2 support such case ?
i have use ffprobe export packets info: https://drive.google.com/file/d/100SW1W_BW_25yEDp0CZR6N_BDEeCyMHp/view?usp=sharing

**Comment by myrsloik** [comment]
No sample file provided.
