### ISSUE TITLE
Graphical artifacts when decoding H.264 lossless

### ISSUE THREAD

**Issue by Ilya87** [FFMS/ffms2#349]
![eva avs_snapshot_00 02_ 2019 07 24_00 55 02](https://user-images.githubusercontent.com/1446573/61750357-dc640280-adad-11e9-93d5-f26b741589c1.png)
![eva avs_snapshot_00 04_ 2019 07 24_00 55 33](https://user-images.githubusercontent.com/1446573/61750358-dcfc9900-adad-11e9-8965-9ae34cc1f3fc.png)

https://yadi.sk/i/mVwRqLMsummGCQ

ffmpeg -c:v libx264 -crf 0 -preset slow
when decoding using MPC-BE, K-Lite Codec Pack codecs, no artifacts appear.

**Comment by sneaker2** [comment]
Short version:
This is a known problem of old ffmpeg. It is fixed once you build ffms2 with a recent version of ffmpeg.


Long version:
[https://forum.videohelp.com/threads/393667-Decoding-errors-on-my-encode#post2554722](https://forum.videohelp.com/threads/393667-Decoding-errors-on-my-encode#post2554722)

**Comment by Ilya87** [comment]
> build ffms2 with a recent version of ffmpeg
Where I can DOWNLOAD ffms2 with a recent version of ffmpeg?

**Comment by sneaker2** [comment]
Try:
[https://forum.doom9.org/showthread.php?p=1883746#post1883746](https://forum.doom9.org/showthread.php?p=1883746#post1883746)

Note these builds are unofficial by third parties and may introduce other problems.
