### ISSUE TITLE
A/V desync for certain mkv file after 4783c02

### ISSUE THREAD

**Issue by wangqr** [FFMS/ffms2#350]
For certain MKV files, the audio and video are not synchronized. This happens in [2.31.0](https://github.com/FFMS/ffms2/tree/aaf4cc0802aef7ca45cb063794e95693d27f69d5) but not in [2.23.1](https://github.com/FFMS/ffms2/releases/tag/2.23). Git bisect shows that 4783c0260929a05334c81643f2232cff1e8bd4ca is the first bad commit.

This table shows the track length in Aegisub after loading the file:

|                                          | Load MKV with FFMS2           | Remux to MKV[1] then load with FFMS2           | Remux to MP4[2] then load with FFMS2 | Reencode to MKV[3] then load with FFMS2 |
|------------------------------------------|-------------------------------|-------------------------------|-----------------------------------|--------------------------------------|
| 68895b7186556b5fea0f32b5b64645cb1b13de3f | 1:10:38                       | 1:10:38                       | 1:10:38                           | 1:10:38                              |
| 4783c0260929a05334c81643f2232cff1e8bd4ca | Video: 1:10:38 Audio: **1:10:40** | Video: 1:10:38 Audio: **1:10:40** | 1:10:38                           | 1:10:38                              |

[1] `ffmpeg -i test.mkv -c copy exp.mkv`
[2] `ffmpeg -i test.mkv -c copy exp.mp4`
[3] `ffmpeg -i test.mkv exp.mkv`

The file can be played with MPC-HC 1.7.13 (e37826845) without issue. The version of ffmpeg used to remux/reencode and linked to ffms2 is 4.2.1-win64-shared downloaded from https://ffmpeg.zeranoe.com/builds/

Original issue: https://github.com/wangqr/Aegisub/issues/22
I'm not able to provide the test video, but you can find the MediaInfo of that mkv in the original issue linked above. I can do other tests if needed.

**Comment by wangqr** [comment]
https://ftp.wangqr.tk/tmp/clip.mkv (will be deleted shortly after)

**Comment by wangqr** [comment]
[clip.zip](https://github.com/FFMS/ffms2/files/3981749/clip.zip)

**Comment by Ristellise** [comment]
Any Updates/Fixes for this specific issue?

**Comment by vxzms** [comment]
I think new option `FillGaps` also fix the problem, I try [FFMS3000 test1](https://forum.doom9.org/showthread.php?p=1949983#post1949983), it’s look fine.

**Comment by myrsloik** [comment]
Possibly fixed
