### ISSUE TITLE
Lambda as a TIndexCallback?

### ISSUE THREAD

**Issue by wrosecrans** [FFMS/ffms2#353]
Is there any way to attach a callback during indexing using a C++ lambda, or std::function?  As near as I can tell, the public API having a C interface makes it impossible to use anything but a straight C function pointer, but I'm not sure if I'm missing anything obvious and/or clever to make the callback API more convenient from a C++ application

**Comment by myrsloik** [comment]
There's a reason you have a data pointer you can pass along. You can also pass stateless lambdas if you like syntactic sugar.
