### ISSUE TITLE
Support pipe as input?

### ISSUE THREAD

**Issue by 2019NAIC** [FFMS/ffms2#354]
Could ffms2 support UNIX pipe access protocol as [FFmpeg](http://ffmpeg.org/ffmpeg-all.html#pipe) did?

**Comment by dwbuiten** [comment]
Not really, no. FFMS2's entire existence is for frame accurate seeking, and it requires an index to do so. If you want a pipe, I would suggest just using FFmpeg itself.

**Comment by Trung0246** [comment]
Quick question: I'm currently trying to use vapoursynth and attempting to make vapoursynth reading from stdin pipe input. However most of the document suggesting to use ffms2 which in fact ffms2 did not support pipe input read by referring to this issue. Is it possible or do I have to do something else with vapoursynth?
