### ISSUE TITLE
preparing ffms2 for x264 failed

### ISSUE THREAD

**Issue by Patman86** [FFMS/ffms2#358]
Hi,

I have a problem when i want to prepare ffms2 for x264. I think there is a problem with ffmpeg (libavcodec, libavformat etc.). Preparing ffmpeg and lsmash works fine and when I start compiling ffms2 the check for ffmpeg libs fails. The libs exists! Any solution?

**Comment by dwbuiten** [comment]
You have given no details on what fails and how or what 'preparing' means in this context.

**Comment by Patman86** [comment]
I wanted to update my x264 version with ffms and lsmash support. It worked wonderfully in the past. Here is the [error log](https://pastebin.com/L05cXwJP) when compiling the ffms libs.

**Comment by dwbuiten** [comment]
Are you sure your PKG_CONFIG_LIBDIR / PKG_CONFIG_PATH is set propetly to point to the right place? Also `config.log` is more useful. What is `/d/repos/x264/Build_ffms2_x264.sh`?

**Comment by Patman86** [comment]
Yes, i'm sure 

![grafik](https://user-images.githubusercontent.com/54327252/78831387-d79db800-79e9-11ea-896b-fe403223323b.png)

/d/repos/x264/Build_ffms2_x264.sh - Build_ffms2_x264.sh is my script (bash file). I can also type bash Build_ffms2_x264.sh with same result. This (/d/repos/x264/Build_ffms2_x264.sh) was written because I dragged and dropped the file onto the Mintty console. In the screenshot you can see that the PKG_CONFIG_LIBDIR / PKG_CONFIG_PATH are in the correct folder. And as I mentioned before, I used the script the same way before. I just updated all other repos (ffmpeg, lsmash and ffms2). Hence the suspicion that it is more due to ffmpeg than to ffms2.

**Comment by qyot27** [comment]
Those two `config.log`s are identical.  Checksum and everything.

**Comment by dwbuiten** [comment]
I think you may have uploaded the same config.log twice; both those files are identical.

**Comment by Patman86** [comment]
Fixed!

**Comment by qyot27** [comment]
There's definitely a problem in your MSys2 environment.  The differences in the config.log versions point primarily to stuff that should be on the $PATH not being there, and other locations shifting to other parts of the filesystem.

I even tested this last night - I updated MSys2, built FFmpeg, and then configured FFMS2 from git.  It found the FFmpeg libs just fine (although the build choked on linking ffmsindex due to -municode/WinMain issues...I thought that was fixed?).

**Comment by Patman86** [comment]
> 
> 
> There's definitely a problem in your MSys2 environment. The differences in the config.log versions point primarily to stuff that should be on the $PATH not being there, and other locations shifting to other parts of the filesystem.

Hey you are right, thanks. After reinstalling Msys2 and updating everything works fine.
