### ISSUE TITLE
Major API changes even with minor version change

### ISSUE THREAD

**Issue by bitstreamout** [FFMS/ffms2#359]
-#define FFMS_VERSION ((2 << 24) | (23 << 16) | (0 << 8) | 0)
+#define FFMS_VERSION ((2 << 24) | (31 << 16) | (0 << 8) | 0)

-typedef enum FFMS_Sources {
-typedef enum FFMS_CPUFeatures {
-typedef enum FFMS_ColorPrimaries {
-typedef enum FFMS_TransferCharacteristic {
-typedef enum FFMS_ColorSpaces {
-typedef int (FFMS_CC *TAudioNameCallback)(const char *SourceFile, int Track, const FFMS_AudioProperties *AP, char *FileName, int FNSize, void *Private);

and this breaks the build of aegisub here

**Comment by dwbuiten** [comment]
This indeed looks like it needs a Major/SONAME bump. Can you be a bit more specific on which commit this is, and if it is before or after the last release?

**Comment by bitstreamout** [comment]
This what had been specfied in the changelog
```
- Refresh ffms2-pkgconfig.patch
- Update to version 2.23+202.ga9e8f73:
  * See changelog at https://github.com/FFMS/ffms2/commits/master
```

**Comment by dwbuiten** [comment]
That's a pretty useless changelog entry (and not from FFMS2).

`git blame` reveals it's actually a number of commits, all of which happened over two years ago... I guess the deprecated stuff had few enough users that nobody noticed until now.

**Comment by sebastinas** [comment]
While preparing 2.40 for Debian, I noticed that that version dropped even more functions without bumping the SONAME please. Could you please prepare a release with a new SONAME, e.g., `VERSION_INFO="5:0:0"` in `configure.ac`?

**Comment by myrsloik** [comment]
Major version and configure.ac version bumped so at least the next release will have that.
