### ISSUE TITLE
linux version of ffms2 doen't support avisynth

### ISSUE THREAD

**Issue by bill-baklushi** [FFMS/ffms2#361]
Hello.
I compiled avi2yuv and libavisynth+ for my ubuntu. Linux version of libavisynth.so not supports AviSource (because of DirectShow), so I found ffms2. 

Last version doesn't export AvisynthPluginInit3 at all, only VapourSynthPluginInit.
And ubuntu's version (from package libffms2-dev) does't export it too.

Is any way to configure ffms2 with avisynth support on linux?

**Comment by myrsloik** [comment]
Se the most recent commits. It should be possible to enable.

**Comment by bill-baklushi** [comment]
I tried 
./autogen.sh --enable=AVISYNTH
but
configure: error: unrecognized option: `--enable=AVISYNTH'

**Comment by myrsloik** [comment]
1. Run autogen.sh with no arguments
2. ./configure --enable-avisynth

**Comment by bill-baklushi** [comment]
Now compilation fails:
src/avisynth/avssources.h:28:10: fatal error: avisynth.h: No such file or directory

**Comment by bill-baklushi** [comment]
It works:
autogen.sh --enable-avisynth CPPFLAGS="-I/usr/local/include/avisynth/"
Thanks.
