### ISSUE TITLE
Enable setting avcontext options

### ISSUE THREAD

**Issue by emcodem** [FFMS/ffms2#363]
Hello and of course thanks a lot for this magnificient project!
Would it be possible for you to add the ability to pass avcontext options? In my case, i need those 2 parameters set in order to be able to decode quicktime reference files:
 -use_absolute_path 1 -enable_drefs 1 

My working ffmpeg command looks like this: ffmpeg -y  -use_absolute_path 1 -enable_drefs 1  -i ...inputfile... ...

**Comment by myrsloik** [comment]
Implemented
