### ISSUE TITLE
Can only the txt file be created, not ffindex?

### ISSUE THREAD

**Issue by MMasutin** [FFMS/ffms2#365]
I didn't see any relevant switch.
With one media file so far, the txt file was not created.

**Comment by MMasutin** [comment]
Without the need to generate the ffindex file, can the process run faster?

**Comment by myrsloik** [comment]
No

**Comment by MMasutin** [comment]
Sometimes kf.txt is not created along with the ffindex file. If the key frames can also be derived from the ffindex file or tc.txt, how can I do it?
