### ISSUE TITLE
Exposing RotationMatrix/Flip to vapoursynth

### ISSUE THREAD

**Issue by Bellaktris** [FFMS/ffms2#366]
Hi, do you think it would be possible to expose RotationMatrix/Flip video properties to Vapoursynth plugin? As frame properties or as additional output from plugin.

**Comment by myrsloik** [comment]
Actually I was thinking about simply applying the flip/rotation automatically but never got around to it. I assume you only want the information to apply it yourself, right?

**Comment by Bellaktris** [comment]
For my use-cases I would be fine with automatic application too.

**Comment by myrsloik** [comment]
Now the Rotation and Flip frame properties are set. Have fun.

**Comment by Bellaktris** [comment]
Awesome, thank you
