### ISSUE TITLE
If kf.txt is not created, can I get KF from .ffindex or tc.txt?

### ISSUE THREAD

**Issue by MMasutin** [FFMS/ffms2#368]
Sometimes kf.txt is not created along with the ffindex file. Can frame numbers be derived as text from .ffindex or tc.txt?

**Comment by dwbuiten** [comment]
> Sometimes kf.txt is not created along with the ffindex file. 

Only if not asked for.

> Can frame numbers be derived as text from .ffindex or tc.txt?

I guess it depends on your usecase - why do you want to do this?

The easiest way is simply to reindex the file, obviously.

The `.ffindex` file can obviously be parsed as it is, if you need to use it in some programmatic way, e.g. I wrote a parse before in Go: https://github.com/dwbuiten/dumpindex

**Comment by MMasutin** [comment]
Thank you!
>Only if not asked for.
No, '-k' is there, but very rarely kf.txt is just not created, reason unknown. I use frame numbers for cutting. If kf.txt is absent, I wondered wether there was a way to use .ffindex or tc.txt to get at key frames as text. Apparently, your dumpindex can do this but probably in a way that exceeds my knowledge or purpose. Originally, FFMS was recommended as a source of values for key frames more accurate than, say, PotPlayer. It is.

**Comment by myrsloik** [comment]
No hint as to when "sometimes" is. Closing.
