### ISSUE TITLE
Audio from MKV is out of sync and shows crackling noises

### ISSUE THREAD

**Issue by Roemer** [FFMS/ffms2#374]
A video file (mkv) I try to use in dubbing has strange issues:
- The audio is out of sync by a few frames
- The audio has audible cracking noises either when played with ffplay or even when encoded with ffmpeg

The AVS script only contains the bare minimum:
`FFmpegSource2("video.mkv", vtrack=-1, atrack=-1)`

If I first encode the audio from the original video file to like mp3 with ffmpeg and then use this mp3 as audio track, everything is fine.
So I guess this plugin cannot handle that audio for some reason. Althoug it seems to be failry normal:
`Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)`

Do you need any more information to look at it? In worst case, I can provide the audio file.

Edit: Might be related to #370

**Comment by myrsloik** [comment]
Add an option to disable/enable audio gap filling and by default enables it based on container.
