### ISSUE TITLE
Question: Does ffmsindex need -municode linker option in Win32?

### ISSUE THREAD

**Issue by Biswa96** [FFMS/ffms2#375]
I was compiling this project with msys2/mingw-w64 toolchain ([link][1]). I have to add the `-municode` linker flag for ffmsindex, maybe for `wmain()` function. Otherwise, there is a linking error `undefined reference to 'WinMain'`. Here is my proposed diff.

```diff --git a/Makefile.am b/Makefile.am
index 61d9921..88f9c27 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -55,6 +55,7 @@ include_HEADERS = $(top_srcdir)/include/ffms.h $(top_srcdir)/include/ffmscompat.
 
 bin_PROGRAMS = src/index/ffmsindex
 src_index_ffmsindex_SOURCES = src/index/ffmsindex.cpp
+src_index_ffmsindex_LDFLAGS = -municode
 src_index_ffmsindex_LDADD = src/core/libffms2.la
 
 .PHONY: test test-build test-clean test-sync test-run
```

But I am not sure if this is required or I am missing something. I can provide any further information, if required.

[1]: https://github.com/msys2/MINGW-packages/pull/7921

**Comment by myrsloik** [comment]
No idea. The official build configuration on windows is MSVC (and possibly clang-cl nowadays) and everything else is your own problem to solve.
