### ISSUE TITLE
Use existing index of MXF files

### ISSUE THREAD

**Issue by emcodem** [FFMS/ffms2#377]
Hi, 
thanks for this great project, it is still a great thing after all these years!
I wonder how much work it would be to speed up processing of mxf files that carry already an existing index... what you think would be easier to do: Work in the core of ffms2 or provide a special indexing program that reads the existing index from mxf and translates it into a ffmsindex file?

**Comment by myrsloik** [comment]
Can't be done in the way you describe. Same thing can be said about AVI files as well. Feel free to make your own source filter that simply trusts the seeking in FFmpeg => done.
