### ISSUE TITLE
warning: implicit declaration of function 'avcodec_register_all'

### ISSUE THREAD

**Issue by RRINNLONGINUS** [FFMS/ffms2#379]
Tried compiling through MSYS2+MinGW-w64 with `./configure --with-pic --enable-avisynth --enable-shared` and it said could not link with FFMPEG because it doesn't work despite the FFMPEG I compiled and installed was fully functional. Said to check `config.log` and this seemed to be the point of interest.

> configure:17062: checking for FFMPEG
> configure:17069: $PKG_CONFIG --exists --print-errors "libavformat >= 53.20.0 libavcodec >= 53.24.0 libswscale >= 0.7.0 libavutil >= 51.21.0 libswresample >= 1.0.0"
> configure:17072: $? = 0
> configure:17086: $PKG_CONFIG --exists --print-errors "libavformat >= 53.20.0 libavcodec >= 53.24.0 libswscale >= 0.7.0 libavutil >= 51.21.0 libswresample >= 1.0.0"
> configure:17089: $? = 0
> configure:17147: result: yes
> configure:17162: checking whether FFmpeg works
> configure:17182: gcc -o conftest.exe -O3 -Wall -Wextra -IC:/msys64/usr/local/include   -D__STDC_CONSTANT_MACROS  conftest.c  -LC:/msys64/usr/local/lib -lavformat -lavcodec -lswscale -lavutil -lswresample >&5
> conftest.c: In function 'main':
> conftest.c:30:17: warning: implicit declaration of function 'avcodec_register_all' [-Wimplicit-function-declaration]
>    30 |                 avcodec_register_all();
>       |                 ^~~~~~~~~~~~~~~~~~~~
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cced0LU4.o:conftest.c:(.text.startup+0xa): undefined reference to `avcodec_register_all'
> collect2.exe: error: ld returned 1 exit status
> configure:17182: $? = 1

Highly likely an issue on my side but anyways I would appreciate it if someone could enlighten me with a possible solution.

**Comment by myrsloik** [comment]
Maybe that function was finally removed since it's been deprecated for years. Is your FFmpeg library very recent?

**Comment by RRINNLONGINUS** [comment]
Well, yes, supposedly. Since I got the source code directly from the [official site](https://www.ffmpeg.org/) and directly compiled it. I attempted to compile FFMS2 to enable FFMS support in x264 that I will build after I'm done with FFMS2, in which after this is done I would recompile FFMPEG with all the libraries I want enabled.

Actually, this is my first time compiling things and decided to start with MSYS2+MinGW-w64. I'm still learning, and have learned a lot for starters I guess (damn there were a lot of issues on the way here)

**Comment by myrsloik** [comment]
Great decision to try your luck with the dark compilation arts. Unfortunately FFMS2 isn't very well maintained nowadays and I don't have time to fix it for a while. Try with a one year old version of FFmpeg or pick another project to try to compile instead since this isn't a good beginner project right now.

**Comment by RRINNLONGINUS** [comment]
I see. So all I need is an older FFMPEG and I should be able to compile FFMS2 without fatal errors then.

Just found out that all I need is a vanilla x264 for my FFMPEG to be compiled with a working libx264 encoder; no need FFMS2 support on x264 prior to compiling. But still I want to try to build a standard x264 for fun. Thank you for the suggestion! I'll try it out and report back if there are any issues (definitely will make sure it was not induced by me)

**Comment by dwbuiten** [comment]
It's an easy fix... I will send a PR.

(I have been using a fork of FFMS2 in my personal github account but it has too many ugly upstreamable hacks.(

**Comment by dwbuiten** [comment]
Upon looking closer, this is already in `ffmscompat.h` in master. Are you not building FFMS2 git master?

**Comment by dwbuiten** [comment]
Oh i see, it's in configure. Fixing.

**Comment by dwbuiten** [comment]
https://github.com/FFMS/ffms2/pull/380

**Comment by RRINNLONGINUS** [comment]
Sorry I was offline for a bit there.
Yeah, now it passed the `./configure` part but unfortunately I stumbled upon a new error while executing `make`

Will open a new issue for that in case I can't find a workaround
