### ISSUE TITLE
IPCM Not detected as pcm_s24be and decoded accordingly by FFAudioSource

### ISSUE THREAD

**Issue by FranceBB** [FFMS/ffms2#381]
Summary of the bug:
IPCM audio files muxed in MP4 are not correctly detected as pcm_s24be and decoded accordingly.

How to reproduce:

```
video=FFVideoSource("Z:\IPCM_Sample.MP4")
audio=FFAudioSource("Z:\IPCM_Sample.MP4")
AudioDub(video, audio)
```

Expected behavior: decode IPCM as pcm_s24be (PCM signed 24-bit big-endian)

Actual behavior: FFAudioSource audio codec not found

How to workaround:

ffmpeg.exe -c:a pcm_s24be -i "Z:\IPCM_Sample.MP4" -acodec pcm_s24le -ar 48000 -ac 2 -y out1.wav

and then index the newly created PCM signed 24-bit little-endian file muxed in .wav

ffms2 version: 2.40
built on 22/08/2020 12:29 PM GMT+1

IPCM Sample: ​https://we.tl/t-UkEK5c94if
Decoded and re-encoded to PCM 24bit little endian audio: ​https://we.tl/t-4yTKInyzmt

Mediainfo:
![image](https://user-images.githubusercontent.com/18946343/117267135-ddb0d300-ae4d-11eb-90da-56c06b2cb3ef.png)

**Comment by myrsloik** [comment]
Did you try with a more recent compile of FFMS2 by someone else? This sounds like something an old FFmpeg version would cause.

**Comment by FranceBB** [comment]
Tried on a new version compiled on Doom9, very same behavior.

**Comment by FranceBB** [comment]
Hi there.
I reached out to FFMpeg as well. Let's see if they're gonna fix it and I'll let you know.
https://trac.ffmpeg.org/ticket/9219

**Comment by myrsloik** [comment]
Fixed upstream according to ffmpeg ticket.
