### ISSUE TITLE
Possible support for Vulkan Video?

### ISSUE THREAD

**Issue by wrosecrans** [FFMS/ffms2#382]
I know one of the design goals of ffms2 is to keep the API simple and not expand the scope too much, but I figured it couldn't hurt to throw the question out there as a feature request.

Vulkan just introduced a new extension for doing cross-platform video decoding with the GPU that pops out a VkImage you can use as a texture on the GPU, or map and copy back to host memory:  https://www.khronos.org/blog/an-introduction-to-vulkan-video  The example uses ffmpeg to parse and demux the raw video, and Vulkan to do the actual video decompression.  But obviously poking around in raw ffmpeg guts to handle stuff like seeking is a pain in the neck.

So, would there be any interest in eventually adding Vulkan support to ffms2 so I could use the simple FFMS_GetFrame() API to let FFMS handle all of the indexing/seeking/whatever so I can get a frame on the GPU as easily as on the CPU?

Dunno if it would be more obvious to have FFMS_Frame returned by FFMS_GetFrame carry a reference to the Vulkan image handle, or have a separate FFMS_GetVkImage() function.  Hardware decoding for FFMS2 has been avoided in the past, but since the Vulkan Video stuff theoretically supports any platform and any kind of device, it might be the best "bang for the buck" for this sort of thing since it potentially replaces a whole bunch of device and platform specific API's.  There are interop extensions so that for example, people writing mostly-OpenGL apps could get access to the Vulkan texture on the GPU to use for OpenGL rendering, so supporting Vulkan Video wouldn't necessarily only be useful for people writing their whole app with Vulkan.

**Comment by myrsloik** [comment]
It could be an interesting modification but we already have enough trouble just to keep FFMS2 working as is. Wrangling the FFmpeg API is truly a fate worse than death.

**Comment by myrsloik** [comment]
Maybe some other year when I have the time. It's an interesting idea but without a nice evaluation of which platforms and gpus are supported nobody will go near it.
