### ISSUE TITLE
MKV ’s audio and video are out of sync

### ISSUE THREAD

**Issue by vxzms** [FFMS/ffms2#387]
I get an error when I open a video in Aegisub, the mkv ’s audio and video are out of sync. The commit 95c0bd152dca30e74769e84836ee2710e4bf56db may be fix this error because I get a sync video when I use his `ffms2.dll` from [AegisubDC](https://github.com/Ristellise/AegisubDC).

I am not sure if this error can be reproduced in Avisynth because I don’t know how to test.

ffms2 version: 2.40
error video: [MEGA link](https://mega.nz/file/yjoCVTTD#qRj3WK6DTEq0u1VfCyBORNu-0k1XQcuEnLmmP3E8avc)

**Comment by myrsloik** [comment]
Add an option to disable/enable audio gap filling and by default enables it based on container
