### ISSUE TITLE
When Indexing a WAV which is larger than 2 GB, the audio is silent from a certain point onward

### ISSUE THREAD

**Issue by FranceBB** [FFMS/ffms2#389]
One of my colleagues reported that when Indexing a WAV which is larger than 2 GB, the audio is silent from a certain point onward even if he's using the x64 build for Avisynth.
I wonder if rf64 (which would be the extension needed to come around the original wav size limit) has been implemented in FFAudioSource().
Anyway, ffmpeg seems to support wav's bigger than 2 GB, even when the rf64 extension is not used in the source file, in fact in FFMpeg decoding works fine.
Here is a way to quickly create a test wav file to reproduce the problem:

`ffmpeg -f lavfi -i "sine=frequency=1000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=2000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=3000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=4000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=5000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=6000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=7000:sample_rate=48000:duration=3600" -f lavfi -i "sine=frequency=8000:sample_rate=48000:duration=3600" -filter_complex amerge=inputs=8 c:\temp\out.wav`

Indexing it with FFAudioSource() causes the problem.

The problem doesn't occur with WAVSource().

**Comment by tebasuna51** [comment]
Does not make sense index a pcm samples wav, to locate a sample in a file you only need know the number of bytes per sample and multiply.

BTW you can use RaWavSource from NicAudio to support WAV files bigger than 4 GB, ans also RF64 or W64

**Comment by FranceBB** [comment]
Of course I can use NicAudio(), but the thing is that one of my colleagues used FFAudioSource() by mistake and found the issue so he reported it to me and I was like: first of all, demux and use WAVSource(), second of all I might as well just report it to the FFAudioSource () developers to get it fixed.

**Comment by myrsloik** [comment]
Works properly here. Maybe it depends on the used FFmpeg version used when building?
