### ISSUE TITLE
Decoder/demuxer options that are kinda useful to expose/change

### ISSUE THREAD

**Issue by myrsloik** [FFMS/ffms2#390]
Demuxer:
mov/mp4/3gp: advanced_editlist (always set to 0)
mov/mp4/3gp: use_absolute_path
mov/mp4/3gp: enable_drefs

Decoder:
ac3: drc_scale

**Comment by dwbuiten** [comment]
We really should not hard set advanced_editlist to 0, it has quite some uses, and we even have tests for it - I, at least, use it.

Further, I am not a fan of the new API with specific boolean options... we should really properly expose an API that lets API users set AVOptions themselves, while having some sane defaults. It would let me e.g. get rid of all my networking patches in my local branch, too.

**Comment by myrsloik** [comment]
resolved in a better way
