### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by marillat** [FFMS/ffms2#399]
Hi,

Sorry to open an issue for that, I don't know who to ask,
but it is possible to have a new release ?

My motivations : the new library soname and the last release is 2 years old.

Christian

**Comment by jlw4049** [comment]
I have no clue why the dev's haven't updated the release. However if you look here there is an updated version from a different dev. Works good! https://forum.doom9.net/showpost.php?p=1967796&postcount=2700

**Comment by myrsloik** [comment]
It happens when it happen. Developing this is a hobby of pure pain. Have a nice day.
