### ISSUE TITLE
Reading Dolby Vision RPU from m2ts

### ISSUE THREAD

**Issue by YomikoR** [FFMS/ffms2#401]
I built FFMS2 on Windows with FFmpeg 5.0.1 for the latest feature in master. When indexing a blu-ray m2ts with DV profile 7, FFMS2 adds global parameters to frame properties but not the frame-dependent DolbyVisionRPU.
![unknown](https://user-images.githubusercontent.com/64504948/164951385-e1b27c9c-1843-483f-aeb9-953906b5f9c1.png)
Things work as expected if indexing the output of MakeMKV instead.
![unknown](https://user-images.githubusercontent.com/64504948/164951427-c3e23a71-6011-43ac-a75f-1145c5f1d782.png)
(Same frame in my previewer btw)

**Comment by dwbuiten** [comment]
I think MakeMKV may be merging the MEL/EL and base layer - IIRC UHD Blu-rays have their RPUs in a separate stream (the MEL/EL stream), so opening the m2ts directly with FFMS2 would require you to use that stream to get the RPUs.

CC: @quietvoid

**Comment by quietvoid** [comment]
Yes, with m2ts you have to use the second video track.
I don't know if the plugin allows track selection.

**Comment by YomikoR** [comment]
Thanks. The data can be found with `track=1`.
