### ISSUE TITLE
VC-1 decoding not frame-accurate unless decoding from beginning.

### ISSUE THREAD

**Issue by damian101** [FFMS/ffms2#406]
I have a frame accuracy VC-1 issue when using Av1an. Chunks encoded are offset by one frame, causing inefficiency. I assume that during scene detection, VC-1 is decoded correctly, but during encoding, VC-1 decoder reports frames offset by +1.

I'm using Arch Linux.

**Comment by myrsloik** [comment]
No sample file or test case provided.
