### ISSUE TITLE
Problem if the file path has some special character

### ISSUE THREAD

**Issue by manuelrn** [FFMS/ffms2#414]
Hello!
I wanted to report a bug that occurs in the latest versions and did not occur in older versions.

The problem is that when I use FFVideoSource(), if the file path has some special character (for example letters like "á", "é", "í", "ó", "ú", "ñ", etc.) it fails and can't find the file.
This happens in 1031029 and 780e931, however in 90975ec (and I think older versions as well) it works fine without any problem.

It would be greatly appreciated if it could be fixed and work like old versions again.
Thank you so much!

**Comment by myrsloik** [comment]
Nothing related to filename handling has changed between those revisions at all. Actually it must be 5+ years since anything was changed related to that. Probably has something to do with the character encoding of the avisynth script.
