### ISSUE TITLE
Expose `log2_chroma_h` and `log2_chroma_w` in `FFMS_Frame`

### ISSUE THREAD

**Issue by Luni-4** [FFMS/ffms2#433]
It would be helpful to expose `log2_chroma_h` and `log2_chroma_w` values as  `FFMS_Frame` fields. This could help in retrieving frame data.

**Comment by dwbuiten** [comment]
Hmm to what end? It already has per-plane strides, and AVFrame themselvess doesn't expose them directly either. If you want them, they're accessible the same way they are from AVFrame - `av_pix_fmt_desc_get` on the format from the FFMS_Frame.

**Comment by myrsloik** [comment]
You have to use FFmpeg to get that information. There's no reason for us to reimplement things

**Comment by Luni-4** [comment]
I see. In my case, it would just be helpful to expose the output of the FFMpeg functions as `FFMS_Frame` fields, in this it is not necessary to import `FFMpeg` as dependency at all.
