### ISSUE TITLE
`Colorspace` field in `FFMS_Frame`

### ISSUE THREAD

**Issue by Luni-4** [FFMS/ffms2#436]
Reading the [ffms2](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-api.md) documentation I've found a reference to the [FFMS_ColorSpaces](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-api.md#int-colorspace) structure, but I cannot find that anywhere in the code. How should the `ColorSpace` field of the `FFMS_Frame` structure be treated? As the output of the [FFMS_GetPixFmt](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-api.md#ffms_getpixfmt---gets-a-colorspace-identifier-from-a-colorspace-name)  function?

**Comment by myrsloik** [comment]
Yes, use FFMS_GetPixFmt with the FFmpeg name of the format.
