### ISSUE TITLE
Outdated version on crates.io

### ISSUE THREAD

**Issue by mipimipi** [FFMS/ffms2#438]
The crate version on crates.io is outdated and thus it cannot be downloaded by cargo automatically. Could you please update it?
Thanks!

**Comment by myrsloik** [comment]
We don't maintain packages. Report the issue to the packager directly.

**Comment by seiya-git** [comment]
You need ask @Luni-4

**Comment by mipimipi** [comment]
Just contacted @Luni-4 via mail. Thanks!
