### ISSUE TITLE
fpsden-fpsnum don't work properly on RC4

### ISSUE THREAD

**Issue by Hackerpcs** [FFMS/ffms2#443]
I am using [StaxRip](https://github.com/staxrip/staxrip) to mostly encode from lossless SD HuffYUV avi, capturing VHS from ATI 600 USB and JVC HR-S7600EU VCR using AmarecTV. I use "fpsnum=25, fpsden=1" to force PAL 25fps because AmarecTV naturally inserts some frames when needed (start/stop of the tape, empty tape at the end with static, etc) because otherwise the result is less than 25fps, causing audio sync issues.

Using [ffms2-2.40](https://github.com/FFMS/ffms2/releases/tag/2.40), the result correctly is that the duration being adjusted up when using "fpsnum=25, fpsden=1" with the added frames as stated [in the documentation](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-avisynth.md#int-fpsnum---1-int-fpsden--1), e.g. on this ~3h recording, a total duration that before was 186:52, after using "fpsnum=25, fpsden=1" was adjusted up to 186:55

![2 4 fpsden off](https://github.com/FFMS/ffms2/assets/17467335/af22c546-a422-48f4-bef3-bebb9a4840f8)

![2 4 fpsden on](https://github.com/FFMS/ffms2/assets/17467335/aa479c0a-3145-46bb-8166-09252fd4e1f7)

In contrast, if I instead use [5.0-RC4](https://github.com/FFMS/ffms2/releases/tag/5.0-RC4), the arguments don't work properly and the duration isn't adjusted, staying at 186:52 with or without the arguments and the end result has audio sync issues

I can't upload the source file because of its size but here is sample where I intentionally start and stop the tape to make the result have enough inserted frames. Due to the smaller duration the difference isn't that drastic but it there, the frames before (using Staxrip's Preview feature to see the resulting avs script) are 1932 and after if "fpsnum=25, fpsden=1" is used are 1943 which are the correct as seen in the AmarecTV's log (line 3171, "VT=00:01:17.773s(1943f)")

[https://mega.nz/folder/XE4UzAZA#5co2GPSZm-z-j19wv4feKg](https://mega.nz/folder/XE4UzAZA#5co2GPSZm-z-j19wv4feKg)

**Comment by Dendraspis** [comment]
Just a few little additions to this report, that could help:

- [v5.0-RC3](https://github.com/FFMS/ffms2/releases/tag/5.0-RC3) is also affected, so it's not a recent change that causes the issue.
- The media info of the sample file shows:  
```
Frame rate                               : 25.000
Frame rate                               : 25.000 FPS
FrameRate_Num                            : 25
FrameRate_Den                            : 1
Frame count                              : 1944
```
- StaxRip reports the data from `AviSynth+`:  
![image](https://github.com/FFMS/ffms2/assets/50659978/c90586f6-abf4-4ecb-895c-f25c1e5cf15a)
- When setting `fpsnum=25, fpsden=1` the report looks correct:  
![image](https://github.com/FFMS/ffms2/assets/50659978/1f34a9b1-88a8-48d1-9f03-d43a61209e0e)

**Comment by myrsloik** [comment]
Fixed here too

**Comment by Dendraspis** [comment]
Thank you very much.  🙂
