### ISSUE TITLE
Issue in linking process on systems with multiple ffmpeg versions installed

### ISSUE THREAD

**Issue by i0ntempest** [FFMS/ffms2#444]
I have ffmpeg v4 and v6 installed from MacPorts on macOS 14.5. v4 is at the default prefix (`/opt/local`), while v6 is installed in a separate prefix (`/opt/local/libexec/ffmpeg6`). I have prepended `/opt/local/libexec/ffmpeg6/lib/pkgconfig` into pkgconfig search path env variable and the configure script can detect ffmpeg v6 and passes. However after building and installing, binaries are still linked to the old libraries in `/opt/local/lib`. There's probably some sort of bug in the configure process.
Full build log:
[main.log](https://github.com/user-attachments/files/15506928/main.log)

**Comment by dwbuiten** [comment]
Are you sure your v6 libraries are actually in the proper path for ld.so to find (e.g. via `LD_PRELOAD_PATH`)? This sounds more like a runtime issue than a build time issue.

**Comment by i0ntempest** [comment]
I've checked with `otool -L`. Linked libraries are the same wether v4 is available or not after building the software.

**Comment by i0ntempest** [comment]
Turns out this is a problem in MacPorts' build environment, LDFLAGS is missing `-L/opt/local/libexec/ffmpeg6/lib`. Fixed [here](https://github.com/macports/macports-ports/commit/cffdfd20976cf71ecf683fd1827c80fdb9df5f83).
