### ISSUE TITLE
ffms2.dll vdub crash

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#54]
_From [tsunagaru](https://code.google.com/u/114819260630654619836/) on August 25, 2011 13:27:22_

What steps will reproduce the problem? 1. A m2ts Blu-ray source.
2.AVS: o  =  FFMpegSource2("00054.m2ts",atrack=-2)
return o
3. No problem with the indexing.
4. Encode the file using VirtualDub with ffdshow ffv1 codec, fast recompress mode. What is the expected output? What do you see instead? A long movie with more than 160000 frames. Vdub crash at randomly frame 5800-7300 aprox. This is the error:

Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	VirtualDub.exe
  Versión de la aplicación:	1.10.0.0
  Marca de tiempo de la aplicación:	4d150c7c
  Nombre del módulo con errores:	ffms2.dll
  Versión del módulo con errores:	0.0.0.0
  Marca de tiempo del módulo con errores:	4e38cecc
  Código de excepción:	c0000005
  Desplazamiento de excepción:	00025767
  Versión del sistema operativo:	6.1.7601.2.1.0.256.4
  Id. de configuración regional:	3082
  Información adicional 1:	09c1
  Información adicional 2:	09c136bb10f8d1715785a3c075c14dfe
  Información adicional 3:	187d
  Información adicional 4:	187ddc3cd35638f180a4febe01981e33 What version of the product are you using? On what operating system? Win 7 x64, vdub 1.10 32, avisynth 2.6MT 32, ffms2 r517 32 Please provide any additional information below. I try to encode with previous versions of vdub, avs and ffms2. Same results.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=54_

**Comment by myrsloik** [comment]
Works with lavf demuxer so it can be closed
