### ISSUE TITLE
Only the first 32 tracks are indexable

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#56]
_From [fredrik.mellbin](https://code.google.com/u/101301098229517375309/) on August 26, 2011 09:28:57_

Only the first 32 tracks are indexable. The API should be extended to allow access to all tracks for indexing.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=56_

**Comment by myrsloik** [comment]
Fixed in my branch
