### ISSUE TITLE
Interlaced H.264 requires special treatment of repeat_pict

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#83]
_From [kalle.blomster](https://code.google.com/u/112284474385978317423/) on February 13, 2012 18:45:24_

Interlaced H.264 has many issues in FFMS2, especially when using Haali's parser for MPEG-TS. One of these is mysterious frame duplication. This is caused by the following three facts:

1. Haali's parser sometimes returns packets that each contain a single field. The two packets of a field pair seem to have the same PTS in this case.
2. The repeat_pict flag obtained from parsing the frames indicate whether the packet contains a single field (0), a field pair (1), a frame (1) or three fields (2).
3. lavc appears to decode all packets (regardless of content) into full-height frames (when packet only contains a single field, the missing field is presumably taken from the previous frame or something like that).

We clearly need some special handling of this in order to not output duplicated fields/frames and duplicated timestamps.

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=83_

**Comment by myrsloik** [comment]
Probably not relevant anymore since Haali's stuff is gone.
