### ISSUE TITLE
Memory waste

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#98]
_From [fredrik.mellbin](https://code.google.com/u/101301098229517375309/) on August 19, 2012 02:56:42_

On every frame request these variables are saved with SaveString and consume a bit of memory. This can be evaluated only once.
FFPICT_TYPE
FFVFR_TIME

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=98_

**Comment by myrsloik** [comment]
Not an issue anymore
