### ISSUE TITLE
[VC-1] Inaccurate seeking with Trim function 

### ISSUE THREAD

**Issue by tgoyne** [FFMS/ffms2#99]
_From [x264.fhd.benchmark](https://code.google.com/u/106899515495170562050/) on September 15, 2012 03:18:20_

What steps will reproduce the problem? sample -> http://www.mediafire.com/?vsqh444wjb1j8by script 
LoadPlugin("..\ffms2.dll")
video=FFVideoSource("..\video.mkv",threads=1)
video=Trim(video,1216,1400) What is the expected output? What do you see instead? at the begining there are atleast two repeated frames. (1216 is a location of keyframe according to ffindex) What version of the product are you using? On what operating system? r700

_Original issue: http://code.google.com/p/ffmpegsource/issues/detail?id=99_

**Comment by myrsloik** [comment]
Still broken

**Comment by myrsloik** [comment]
Still broken... again

**Comment by myrsloik** [comment]
And it's probably kinda fixed.
